/**
 * Объявления 1–50 (первая половина)
 * budgetType: "per_views" — оплата за просмотры в milestone-формате
 */

export const ADS_DATA_1 = [
  {
    ownerEmail: "autoservice-almaty@seed.kz",
    ownerName: "AutoService Almaty",
    companyName: "AutoService Almaty",
    title: "Ищем автора видео: «Эта женщина проехала 100 000 км — двигатель не тронут»",
    description: "Хотим серию TikTok-видео в формате реальных историй наших клиентов. Пример сценария: «Эта Camry приехала к нам с 100 000 км на счётчике. Двигатель с завода, масло по регламенту — вот почему она до сих пор едет». В конце — мягкая акция: «Первая диагностика у нас — 0 ₸». Нужен автор, который умеет делать вовлекающий нарратив, удерживает досмотр до конца, знает монтаж с цифрами и текстом на экране. Требование: ER не ниже 8%.",
    platform: "TikTok",
    city: "Almaty",
    category: "Avto",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@autoservice_almaty",
    contactWhatsapp: "+77011234567",
    boosts: ["rise"] as string[],
    featured: false,
  },
  {
    ownerEmail: "clean-home-almaty@seed.kz",
    ownerName: "CleanHome Almaty",
    companyName: "CleanHome Almaty",
    title: "«Мы убираем квартиры в Алматы — покажи наш процесс и получи за каждые 50к просмотров»",
    description: "Клининговый сервис ищет автора для TikTok-контента. Формат: «До и после уборки» — снимаем реальные квартиры с согласия клиентов. Честный процесс, профессиональные средства, быстрый результат. В конце: «Первая уборка студии — 7 900 ₸». Нужен автор, умеющий снимать процесс красиво и быстро.",
    platform: "TikTok",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 500 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@cleanhome_almaty",
    contactWhatsapp: "+77011990011",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "belozneg@seed.kz",
    ownerName: "Прачечная Белоснег",
    companyName: "Прачечная Белоснег",
    title: "«Почему ваши вещи садятся» — обучающий Reels для прачечной через боль клиента",
    description: "Нужен автор Reels для Instagram, который расскажет историю от лица клиента: «Я стираю свитер при 60° и он садится — а вот почему и как это предотвратить». В конце — переход к нашей услуге. Формат: образовательный нарратив с хуком в первые 3 секунды. Требование: досмотр от 60%, сохранения в Reels.",
    platform: "Instagram",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@belozneg_laundry",
    contactWhatsapp: "+77017654321",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "autoservice-nur@seed.kz",
    ownerName: "AutoService Nur",
    companyName: "AutoService Nur",
    title: "«Топ-5 самых популярных авто в Астане и где ломаются чаще всего» — YouTube Shorts",
    description: "Ищем автора YouTube Shorts для серии аналитических видео. Идея: берём реальную статистику по маркам авто в Астане, разбираем что чаще всего ломается, сколько стоит ремонт на рынке против нас. Финал каждого видео: «У нас диагностика бесплатно при первом визите». Нужен рассказчик с харизмой и умением подавать цифры живо. Требование: просмотры от 10 000 за 7 дней.",
    platform: "YouTube",
    city: "Astana",
    category: "Avto",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "7 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@autoservice_nur",
    contactWhatsapp: "+77019876543",
    boosts: ["premium"] as string[],
    featured: true,
  },
  {
    ownerEmail: "it-startup@seed.kz",
    ownerName: "IT Startup KZ",
    companyName: "IT Startup KZ",
    title: "«Почему 90% стартапов в Казахстане умирают за год» — TikTok с нашим решением в финале",
    description: "Стартап-продукт для автоматизации учёта ищет автора мемного + аналитического контента. Формат: берём больную тему (провал бизнеса), даём статистику, показываем ошибки. В финале — нативный переход на наш продукт. Автор должен уметь делать быстрый монтаж, цепляющие заголовки, держать ER от 10%.",
    platform: "TikTok",
    city: "Almaty",
    category: "Podkasty",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "8 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@it_startup_kz",
    contactWhatsapp: null,
    boosts: ["vip"] as string[],
    featured: false,
  },
  {
    ownerEmail: "gamecafe-shymkent@seed.kz",
    ownerName: "Game Cafe Shymkent",
    companyName: "Game Cafe Shymkent",
    title: "«Сколько зарабатывает киберспортсмен в Шымкенте?» — YouTube Shorts для игрового кафе",
    description: "Геймерское кафе ищет автора Shorts. Идея серии: интервью с реальными посетителями — «Сколько ты потратил на игры за последний год?». В финале — наша акция: «Первый час в кафе бесплатно для новых гостей». Нужен живой, общительный автор.",
    platform: "YouTube",
    city: "Shymkent",
    category: "Geympley",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@game_cafe_shymkent",
    contactWhatsapp: "+77712345678",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "fitclub-almaty@seed.kz",
    ownerName: "FitClub Almaty",
    companyName: "FitClub Almaty",
    title: "«За 90 дней -10 кг: история нашего клиента» — Reels с трансформацией",
    description: "Ищем автора Instagram Reels для серии трансформаций. У нас есть клиенты, готовые сняться. Формат: «До / После», интервью об ошибках питания и тренировок, итог с цифрами. В конце каждого видео: «Запись на бесплатную первую тренировку через ссылку». Требование: Reels с досмотром от 50%, ER от 8%.",
    platform: "Instagram",
    city: "Almaty",
    category: "Sport",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "6 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@fitclub_almaty",
    contactWhatsapp: "+77019000001",
    boosts: ["rise"] as string[],
    featured: false,
  },
  {
    ownerEmail: "krasota-studio@seed.kz",
    ownerName: "Красота Studio",
    companyName: "Красота Studio",
    title: "«Почему лак держится 3 дня, а не 3 недели» — обучающий Reels для салона",
    description: "Салон красоты ищет автора обучающих Reels. Идея: рассказываем клиентам правду о том, почему гель-лак отслаивается раньше времени. Это образовательный контент, который органически продвигает нашу услугу. В финале: «У нас в салоне каждая процедура с полугодовой гарантией».",
    platform: "Instagram",
    city: "Almaty",
    category: "Krasota",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@krasota_studio_kz",
    contactWhatsapp: "+77011112233",
    boosts: [] as string[],
    featured: true,
  },
  {
    ownerEmail: "dastarkhan@seed.kz",
    ownerName: "Ресторан Дастархан",
    companyName: "Ресторан Дастархан",
    title: "«Это блюдо едят в Казахстане уже 500 лет» — TikTok с историей казахской кухни",
    description: "Ресторан национальной кухни ищет автора для сторителлинг-контента. Формат: берём одно блюдо (бешбармак, куырдак, баурсак), рассказываем его историю с интересными фактами. В финале — наш ресторан как место, где эта традиция живёт. Нужен автор с харизмой, умеющий говорить на казахском и русском.",
    platform: "TikTok",
    city: "Astana",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "10 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@dastarkhan_ast",
    contactWhatsapp: "+77012223344",
    boosts: ["premium"] as string[],
    featured: false,
  },
  {
    ownerEmail: "skygym@seed.kz",
    ownerName: "SkyGym Astana",
    companyName: "SkyGym Astana",
    title: "«Что происходит с телом через 30 дней без сахара» — YouTube Shorts с научными фактами",
    description: "Фитнес-клуб ищет автора Shorts с научным подходом. Идея: берём доказанные факты об отказе от сахара и подаём их живо с инфографикой. Не мотивационная чушь, а конкретика. В конце: «Мы помогаем людям начать — первая неделя бесплатно». Требование: удержание аудитории от 70%.",
    platform: "YouTube",
    city: "Astana",
    category: "Sport",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@skygym_ast",
    contactWhatsapp: "+77013334455",
    boosts: ["vip"] as string[],
    featured: false,
  },
  {
    ownerEmail: "raduga-kids@seed.kz",
    ownerName: "Детский центр Радуга",
    companyName: "Детский центр Радуга",
    title: "«Почему дети, которые рисуют, лучше учатся математике» — TikTok для детского центра",
    description: "Детский развивающий центр ищет автора TikTok. Мы хотим контент, который убеждает родителей через факты: реальные исследования о влиянии творческого мышления на успеваемость. Нативная реклама через образование. В финале: «Запишите ребёнка на первое занятие — бесплатно».",
    platform: "TikTok",
    city: "Almaty",
    category: "Multfilmy",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@raduga_kids_kz",
    contactWhatsapp: "+77014445566",
    boosts: [] as string[],
    featured: true,
  },
  {
    ownerEmail: "shymkent-motors@seed.kz",
    ownerName: "Шымкент Моторс",
    companyName: "Шымкент Моторс",
    title: "«Самые дешёвые запчасти для Toyota — где покупают механики сами для себя»",
    description: "Автосалон в Шымкенте ищет автора YouTube Shorts. Формат: механик объясняет где покупать запчасти и сколько они стоят на рынке vs. у нас. Это строит доверие через инсайдерскую информацию. В финале: «Акция — ТО без наценки на расходники при записи до 20 числа».",
    platform: "YouTube",
    city: "Shymkent",
    category: "Avto",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@shymkent_motors",
    contactWhatsapp: "+77715556677",
    boosts: ["rise"] as string[],
    featured: false,
  },
  {
    ownerEmail: "kztalks@seed.kz",
    ownerName: "KZ Talks",
    companyName: "KZ Talks",
    title: "«Этот предприниматель потерял 10 млн ₸ и начал снова — вот что он сделал иначе»",
    description: "Бизнес-подкаст ищет автора/ведущего для YouTube. Формат: честные разговоры с казахстанскими предпринимателями о провалах, не об успехах. Нам нужен ведущий с умением задавать неудобные вопросы. Требование к кандидату: опыт ведения интервью, понимание бизнес-контекста Казахстана.",
    platform: "YouTube",
    city: "Almaty",
    category: "Podkasty",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "10 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@kztalks_podcast",
    contactWhatsapp: null,
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "pavlodar-pizza@seed.kz",
    ownerName: "Pavlodar Pizza",
    companyName: "Pavlodar Pizza",
    title: "«Мы посчитали: за год павлодарцы съедают 200 000 пицц — вот почему нашу не берут на последнее место»",
    description: "Пиццерия ищет автора TikTok с нарративным подходом. Реальная статистика потребления, сравнение ингредиентов, слепой тест с клиентами. Честный контент, даже если кто-то выберет конкурента — это создаёт доверие. В финале: «Закажи до пятницы — второй размер в подарок».",
    platform: "TikTok",
    city: "Pavlodar",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@pavlodar_pizza",
    contactWhatsapp: "+77186667788",
    boosts: ["vip"] as string[],
    featured: false,
  },
  {
    ownerEmail: "galaxy-tech@seed.kz",
    ownerName: "Galaxy Tech",
    companyName: "Galaxy Tech",
    title: "«Какой смартфон чаще всего ремонтируют в Алматы — и почему это не iPhone» — TikTok-обзор",
    description: "Магазин электроники ищет автора TikTok. Мы хотим серию видео с реальной статистикой ремонтов по маркам (у нас есть данные). Формат: «Мы изучили 500 ремонтов за год — вот что сломалось чаще всего». В конце: «При покупке флагмана у нас — страховка на экран в подарок».",
    platform: "TikTok",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "7 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@galaxy_tech_kz",
    contactWhatsapp: "+77015556677",
    boosts: ["premium"] as string[],
    featured: true,
  },
  {
    ownerEmail: "aktau-fresh@seed.kz",
    ownerName: "Актау Фреш",
    companyName: "Актау Фреш",
    title: "«Этот арбуз проехал 800 км — вот почему наши фрукты другие»",
    description: "Служба доставки фруктов ищет автора Reels в Актау. Документируем путь продуктов от поля до клиента, показываем разницу в сроках хранения. Просветительский контент, который работает как реклама. В финале: «Первая коробка фруктов с доставкой — со скидкой 30%».",
    platform: "Instagram",
    city: "Aktau",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@aktau_fresh",
    contactWhatsapp: "+77292223344",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "kinoclub@seed.kz",
    ownerName: "Кино Club",
    companyName: "Кино Club",
    title: "«Эта сцена из казахского кино изменила отношение к деньгам у 1 млн человек» — нарезки с аналитикой",
    description: "YouTube-канал о кино ищет автора нарезок и эссе. Формат: берём сцену из популярного фильма, разбираем психологию персонажа, делаем выводы для реальной жизни. Не пересказ — глубокий анализ. Требование: удержание аудитории от 65% на видео 60–90 сек.",
    platform: "YouTube",
    city: "Almaty",
    category: "KinoNarezki",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "8 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@kinoclub_kz",
    contactWhatsapp: null,
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "steppe-coffee@seed.kz",
    ownerName: "Steppe Coffee",
    companyName: "Steppe Coffee",
    title: "«Почему кофе в Астане стоит 1500 ₸, а в Европе 300 ₸ — и что это значит для вас»",
    description: "Кофейня ищет автора Reels с образовательным подходом. Разбираем ценообразование кофе в Казахстане — импорт, таможня, аренда. Честный контент, который объясняет нашу цену. В финале: «У нас сейчас сезонный напиток — попробуй со скидкой 20%».",
    platform: "Instagram",
    city: "Astana",
    category: "MuzykaAtmosfera",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@steppe_coffee",
    contactWhatsapp: "+77017778899",
    boosts: ["rise"] as string[],
    featured: false,
  },
  {
    ownerEmail: "musicbox@seed.kz",
    ownerName: "MusicBox KZ",
    companyName: "MusicBox KZ",
    title: "«Дети, которые учатся на гитаре, на 34% лучше решают уравнения» — Reels для музшколы",
    description: "Магазин инструментов ищет автора Reels. Реальные исследования о влиянии музыки на мозг ребёнка, интервью с родителями, живые видео с занятий. Не реклама инструментов — реклама идеи «дать ребёнку инструмент». В финале: «Аренда инструмента на первый месяц — 1 ₸».",
    platform: "Instagram",
    city: "Almaty",
    category: "MuzykaAtmosfera",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 500 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@musicbox_kz",
    contactWhatsapp: "+77018889900",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "kzmemes@seed.kz",
    ownerName: "KZ Memes Hub",
    companyName: "KZ Memes Hub",
    title: "«Когда говоришь «я занят», а сам смотришь TikTok» — мемы про жизнь в Казахстане",
    description: "Медиа-проект ищет автора казахстанских мемов. Нам нужны видео-мемы про ЦОН, пробки в Алматы, разговор с соседями. Не перепакованный контент из России — свежие идеи про нашу жизнь. Требование: охват TikTok от 50 000 за первые 48 часов.",
    platform: "TikTok",
    city: "Almaty",
    category: "Memy",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "6 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@kzmemes_hub",
    contactWhatsapp: null,
    boosts: ["vip"] as string[],
    featured: true,
  },
  {
    ownerEmail: "karaganda-print@seed.kz",
    ownerName: "Karaganda Print",
    companyName: "Karaganda Print",
    title: "«Сколько денег теряет бизнес на плохих визитках» — YouTube Shorts для типографии",
    description: "Типография ищет автора Shorts с бизнес-нарративом. «Плохая визитка стоит вам клиентов — вот реальные данные». Показываем психологию восприятия печатной продукции. В финале: «500 визиток в подарок при заказе от 200 000 ₸».",
    platform: "YouTube",
    city: "Karaganda",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@karaganda_print",
    contactWhatsapp: "+77212223344",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "elite-realty@seed.kz",
    ownerName: "Elite Realty KZ",
    companyName: "Elite Realty KZ",
    title: "«Почему 70% алматинцев покупают квартиру не там» — Instagram Reels с аналитикой рынка",
    description: "Агентство недвижимости ищет автора Reels. «Мы изучили 2000 сделок за 2025 год — вот районы где цена выросла больше всего и почему». Это контент, который люди сохраняют и отправляют друзьям. В финале: «Получите бесплатную консультацию от нашего аналитика».",
    platform: "Instagram",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "7 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@elite_realty_kz",
    contactWhatsapp: "+77016667788",
    boosts: ["premium"] as string[],
    featured: false,
  },
  {
    ownerEmail: "sportzone-pvl@seed.kz",
    ownerName: "SportZone Pavlodar",
    companyName: "SportZone Pavlodar",
    title: "«Сколько стоит не тренироваться — расчёт в деньгах за 10 лет» — TikTok для зала",
    description: "Спортзал ищет автора TikTok с провокационным подходом. Считаем стоимость болезней от сидячего образа жизни против стоимости абонемента. Работает на аудиторию, которая думает что нет денег на зал. В финале: «Месяц пробный — 5 000 ₸».",
    platform: "TikTok",
    city: "Pavlodar",
    category: "Sport",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 500 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@sportzone_pvl",
    contactWhatsapp: "+77187778899",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "animakids@seed.kz",
    ownerName: "AnimaKids Studio",
    companyName: "AnimaKids Studio",
    title: "«Этот ребёнок за 3 месяца научился читать — вот метод, который сработал» — Reels",
    description: "Студия детского развития ищет автора Instagram. Следим за конкретным ребёнком с момента прихода к нам до результата. Объясняем метод простым языком. В финале: «Запишите ребёнка на бесплатное вводное занятие». Требование: ER в Reels от 10%, сохранения от 5%.",
    platform: "Instagram",
    city: "Astana",
    category: "Multfilmy",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@animakids_studio",
    contactWhatsapp: "+77014445566",
    boosts: ["rise"] as string[],
    featured: false,
  },
  {
    ownerEmail: "techhub-kzg@seed.kz",
    ownerName: "TechHub Karaganda",
    companyName: "TechHub Karaganda",
    title: "«Казахстанские разработчики зарабатывают $3000 удалённо — вот как они это сделали»",
    description: "IT-коворкинг ищет автора TikTok. Интервью с людьми, которые перешли в IT без диплома программиста — юристы, учителя, повара. Это вдохновляющий контент с конкретными шагами. В финале: «Мы проводим бесплатный вечер для тех, кто хочет попробовать».",
    platform: "TikTok",
    city: "Karaganda",
    category: "Podkasty",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "6 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@techhub_kzg",
    contactWhatsapp: null,
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "aktausurf@seed.kz",
    ownerName: "AktauSurf Club",
    companyName: "AktauSurf Club",
    title: "«Каспий — единственное место в Центральной Азии, где можно кататься на кайте круглый год»",
    description: "Клуб кайтсерфинга ищет автора для Reels. Показываем статистику ветра на Каспии, сравниваем с мировыми кайт-спотами. Оказывается, Актау — в топе по числу ветреных дней. В финале: «Запишись на пробный урок этой осенью — последние места».",
    platform: "Instagram",
    city: "Aktau",
    category: "Sport",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@aktausurf",
    contactWhatsapp: "+77293334455",
    boosts: ["vip"] as string[],
    featured: false,
  },
  {
    ownerEmail: "greenbox@seed.kz",
    ownerName: "GreenBox Delivery",
    companyName: "GreenBox Delivery",
    title: "«Что происходит с вашей едой за 40 минут доставки» — TikTok с температурным экспериментом",
    description: "Сервис здорового питания ищет автора TikTok. Снимаем реальный эксперимент — замеряем температуру еды при обычной доставке vs. наша термосумка. В финале: «Первая неделя питания от нас с подпиской — минус 20%».",
    platform: "TikTok",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@greenbox_kz",
    contactWhatsapp: "+77015556677",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "shymkent-studio@seed.kz",
    ownerName: "Шымкент Студия",
    companyName: "Шымкент Студия",
    title: "«Этот предприниматель из Туркестана зарабатывает больше алматинца» — подкаст из Шымкента",
    description: "Медиа-студия ищет ведущего/оператора для YouTube-подкаста о региональном бизнесе. Разрушаем миф, что деньги только в Алматы и Астане. Гости — предприниматели из регионов с реальными цифрами.",
    platform: "YouTube",
    city: "Shymkent",
    category: "Podkasty",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@shymkent_studio",
    contactWhatsapp: "+77711112233",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "asiafashion@seed.kz",
    ownerName: "AsiaFashion KZ",
    companyName: "AsiaFashion KZ",
    title: "«Почему казахстанские дизайнеры шьют лучше европейских — но об этом никто не знает» — Reels",
    description: "Казахстанский фешн-бренд ищет автора Instagram. Показываем производство изнутри, интервью с мастерами, сравниваем стоимость труда и качества. Цель — создать гордость за местное. Нужен автор с пониманием fashion-контента.",
    platform: "Instagram",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "7 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@asiafashion_kz",
    contactWhatsapp: "+77016668899",
    boosts: ["premium"] as string[],
    featured: false,
  },
  {
    ownerEmail: "travelkz@seed.kz",
    ownerName: "TravelKZ",
    companyName: "TravelKZ",
    title: "«Место в Казахстане, о котором не знает 99% казахстанцев» — документальные Shorts",
    description: "Тревел-агентство ищет автора YouTube для серии «Неизвестный Казахстан». Каждый выпуск — одно место с историей, фактами, как добраться и сколько стоит. В финале: «Мы организуем тур к этому месту — в октябре последние места».",
    platform: "YouTube",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "10 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@travelkz_official",
    contactWhatsapp: "+77017779900",
    boosts: [] as string[],
    featured: true,
  },
  {
    ownerEmail: "romashka-sushi@seed.kz",
    ownerName: "Ромашка Суши",
    companyName: "Ромашка Суши",
    title: "«Мы дали японскому шефу попробовать нашу шоколадку-маки — вот что он сказал»",
    description: "Суши-ресторан ищет автора TikTok. Слепой тест нетипичной позиции меню с экспертом или случайным прохожим. Искренняя реакция важнее всего. В финале: «Этот ролл только у нас — закажи до пятницы со скидкой 25%».",
    platform: "TikTok",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@romashka_sushi",
    contactWhatsapp: "+77019991122",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "devschool@seed.kz",
    ownerName: "DevSchool KZ",
    companyName: "DevSchool KZ",
    title: "«За сколько можно выучить Python с нуля — мы протестировали на 100 студентах»",
    description: "Онлайн-школа программирования ищет автора YouTube Shorts. Честное исследование нашего продукта — реальные результаты студентов. В финале: «Первый модуль бесплатно — регистрация по ссылке».",
    platform: "YouTube",
    city: "Astana",
    category: "Podkasty",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@devschool_kz",
    contactWhatsapp: null,
    boosts: ["rise"] as string[],
    featured: false,
  },
  {
    ownerEmail: "glowup-beauty@seed.kz",
    ownerName: "GlowUp Beauty",
    companyName: "GlowUp Beauty",
    title: "«Я 30 дней использовала только корейский уход — вот что изменилось» — честный TikTok",
    description: "Магазин корейской косметики ищет автора TikTok-дневника. Ежедневный документальный подход. Реальные наблюдения, плюсы и минусы. В финале: «Скидка 15% на эти позиции по промокоду».",
    platform: "TikTok",
    city: "Almaty",
    category: "Krasota",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "6 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@glowup_beauty_kz",
    contactWhatsapp: "+77018882233",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "prazdnik-almaty@seed.kz",
    ownerName: "Праздник Almaty",
    companyName: "Праздник Almaty",
    title: "«Мы организовали 200 детских праздников — вот самые смешные моменты» — Reels для агентства",
    description: "Агентство праздников ищет автора Instagram Reels. Формат: короткие яркие нарезки с реальных событий — реакция детей, смешные казусы, трогательные моменты. Никаких постановок. В конце: «Закажи детский праздник под ключ — выезд аниматора + декор + фото». Нужен автор с умением снимать живые эмоции.",
    platform: "Instagram",
    city: "Almaty",
    category: "MuzykaAtmosfera",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@prazdnik_almaty",
    contactWhatsapp: "+77011445566",
    boosts: ["vip"] as string[],
    featured: false,
  },
  {
    ownerEmail: "streetfood-almaty@seed.kz",
    ownerName: "StreetFood Almaty",
    companyName: "StreetFood Almaty",
    title: "«Мы показали нашу кухню без редактирования — вот что сказали подписчики» — TikTok",
    description: "Сеть стритфуд-точек ищет автора TikTok. Показываем полностью открытую кухню — готовку в реальном времени без ретуши. Прозрачность работает. Требование: умение снимать в условиях уличной кухни.",
    platform: "TikTok",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@streetfood_almaty",
    contactWhatsapp: "+77011113344",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "zoodom-almaty@seed.kz",
    ownerName: "ZooDom Almaty",
    companyName: "ZooDom Almaty",
    title: "«Ветеринар отвечает: что нельзя кормить кошку — 7 продуктов из вашего холодильника» — TikTok",
    description: "Зоомагазин с ветеринарной аптекой ищет автора TikTok. Формат: ветеринар в кадре отвечает на самые частые вопросы владельцев кошек и собак. Польза + нативная реклама кормов. В финале: «Правильный корм с доставкой — заказывай у нас». Нужен автор, умеющий брать интервью у специалиста.",
    platform: "TikTok",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@zoodom_almaty",
    contactWhatsapp: "+77012224455",
    boosts: ["premium"] as string[],
    featured: true,
  },
  {
    ownerEmail: "kidslearn@seed.kz",
    ownerName: "KidsLearn Online",
    companyName: "KidsLearn Online",
    title: "«Этот 7-летний ребёнок решил задачу 3-го класса за 30 секунд — вот метод, которому мы учим»",
    description: "Образовательная платформа ищет автора YouTube. Снимаем реальных детей, которые прошли наш курс, и даём им задачи на камеру. Никаких постановок — только честный результат. В финале: «Первый месяц обучения — бесплатно при регистрации».",
    platform: "YouTube",
    city: "Astana",
    category: "Multfilmy",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "7 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@kidslearn_online",
    contactWhatsapp: "+77015554433",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "cyclekz@seed.kz",
    ownerName: "CycleKZ",
    companyName: "CycleKZ",
    title: "«Велосипедист проехал из Алматы в Астану за 7 дней — сколько он потратил и что взял с собой»",
    description: "Магазин велосипедов ищет автора YouTube Shorts. Документируем реальное путешествие клиента через Казахстан. Нативно рекламируем снаряжение из нашего магазина. В финале: «Скидка 10% при упоминании видео».",
    platform: "YouTube",
    city: "Almaty",
    category: "Sport",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@cycle_kz",
    contactWhatsapp: "+77016665544",
    boosts: ["rise"] as string[],
    featured: false,
  },
  {
    ownerEmail: "halalfood@seed.kz",
    ownerName: "HalalFood KZ",
    companyName: "HalalFood KZ",
    title: "«Что на самом деле значит халяль на упаковке в Казахстане — проверяем 10 продуктов»",
    description: "Сеть халяль-ресторанов ищет автора TikTok. Проводим независимую проверку сертификации популярных продуктов вместе со специалистом. Это создаёт доверие через экспертизу. В финале: «У нас — сертифицированная халяль-кухня».",
    platform: "TikTok",
    city: "Shymkent",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@halalfood_kz",
    contactWhatsapp: "+77712226677",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "smm-school-almaty@seed.kz",
    ownerName: "SMM Мастерская",
    companyName: "SMM Мастерская",
    title: "«Я веду соцсети для 5 алматинских кафе — вот что реально работает в 2025 году» — TikTok",
    description: "Небольшая SMM-студия ищет автора TikTok для демонстрации своей экспертизы. Формат: «Я ведущий соцсетей малого бизнеса — вот 3 приёма, которые увеличили продажи моих клиентов». Нативная реклама услуг через обучение. В конце: «Хотите так же? Пишите — первый аудит бесплатно». Нужен уверенный, говорящий автор.",
    platform: "TikTok",
    city: "Almaty",
    category: "Podkasty",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@smm_masterskaya",
    contactWhatsapp: "+77012334455",
    boosts: ["vip"] as string[],
    featured: false,
  },
  {
    ownerEmail: "greencity-nursery@seed.kz",
    ownerName: "GreenCity Nursery",
    companyName: "GreenCity Nursery",
    title: "«Этот фикус простоял на подоконнике 3 года без пересадки — вот почему он всё ещё жив» — Reels",
    description: "Питомник растений ищет автора Instagram/TikTok. Реальные истории выживших растений с объяснением, что помогло. В финале: «Купи такой же у нас — и мы научим как за ним ухаживать».",
    platform: "Instagram",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@greencity_nursery",
    contactWhatsapp: "+77013336677",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "tort-almaty@seed.kz",
    ownerName: "Торты от Айгерим",
    companyName: "Торты от Айгерим",
    title: "«Я делаю 30 тортов в месяц на своей кухне — покажи процесс и заработай» — Reels для кондитера",
    description: "Домашняя кондитерская ищет автора Instagram. Показываем полный процесс создания торта — от замеса до финального декора. Без постановки, реальная кухня, реальное время. В конце: «Заказывай торт на любой праздник — от 8 500 ₸». Нужен автор с опытом съёмки в помещении и умением снимать процесс вкусно.",
    platform: "Instagram",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@tort_aigerim",
    contactWhatsapp: "+77011667788",
    boosts: ["premium"] as string[],
    featured: false,
  },
  {
    ownerEmail: "nomad-bbq@seed.kz",
    ownerName: "Nomad BBQ",
    companyName: "Nomad BBQ",
    title: "«Мы жарили мясо 5 разными методами — вот какой оказался лучшим по вкусу»",
    description: "Ресторан с открытым огнём ищет автора Reels. Слепой тест 5 методов приготовления мяса — тандыр, казан, мангал, гриль, духовка. Реальные люди пробуют и голосуют. В финале: «Победивший метод — только у нас. Бронируй стол на выходные».",
    platform: "Instagram",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@nomad_bbq_kz",
    contactWhatsapp: "+77011224455",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "pavlodar-avto@seed.kz",
    ownerName: "Pavlodar Авто",
    companyName: "Pavlodar Авто",
    title: "«Топ-3 запчасти, которые чаще всего меняют неправильно» — TikTok для автомагазина",
    description: "Автомагазин в Павлодаре ищет автора TikTok. Механик объясняет конкретные ошибки при самостоятельной замене расходников. «Вы меняете масло, но не меняете фильтр — вот что происходит». В финале: «У нас всё это по оптовым ценам».",
    platform: "TikTok",
    city: "Pavlodar",
    category: "Avto",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@pavlodar_avto",
    contactWhatsapp: "+77181112233",
    boosts: ["rise"] as string[],
    featured: false,
  },
  {
    ownerEmail: "kino-reviews@seed.kz",
    ownerName: "Kino Reviews KZ",
    companyName: "Kino Reviews KZ",
    title: "«Эта сцена из «Игры в кальмара» объясняет капитализм лучше, чем учебник экономики»",
    description: "YouTube-канал кино-аналитики ищет автора нарезок. Берём популярную сцену из известного сериала и делаем глубокий анализ через социальную, экономическую или психологическую призму. Аудитория — умные люди, которые хотят думать.",
    platform: "YouTube",
    city: "Almaty",
    category: "KinoNarezki",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "8 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@kino_reviews_kz",
    contactWhatsapp: null,
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "aktau-hotel@seed.kz",
    ownerName: "Aktau Hotel Sea",
    companyName: "Aktau Hotel Sea",
    title: "«Что происходит с ценами в отелях Актау в высокий сезон — и когда лучше ехать» — Reels",
    description: "Отель в Актау ищет автора Instagram. Аналитика цен на отдых — когда дешевле всего приехать, почему в июле в 3 раза дороже. В финале: «Забронируй на октябрь прямо сейчас — цены как в мае».",
    platform: "Instagram",
    city: "Aktau",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "8 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@aktau_hotel_sea",
    contactWhatsapp: "+77291113344",
    boosts: ["vip"] as string[],
    featured: false,
  },
  {
    ownerEmail: "qazaqstan-nomads@seed.kz",
    ownerName: "Qazaqstan Nomads",
    companyName: "Qazaqstan Nomads",
    title: "«Казахстанец объездил 40 стран — и говорит, что Казахстан красивее большинства» — YouTube",
    description: "Тревел-проект ищет автора YouTube. Документируем мнение опытного путешественника о природе Казахстана на фоне мировых мест. Не патриотическая пропаганда — честное сравнение. В финале: «Мы организуем экспедиции — осталось 4 места на октябрь».",
    platform: "YouTube",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "8 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@qazaqstan_nomads",
    contactWhatsapp: "+77012225566",
    boosts: [] as string[],
    featured: true,
  },
  {
    ownerEmail: "medclinic@seed.kz",
    ownerName: "MedClinic KZ",
    companyName: "MedClinic KZ",
    title: "«3 симптома, которые казахстанцы игнорируют до инфаркта» — YouTube Shorts для клиники",
    description: "Частная клиника ищет автора YouTube Shorts. Врач в кадре рассказывает про реальные сигналы организма на языке пациента. «Если по утрам болит шея — это не от подушки». В финале: «Запишитесь на профилактический осмотр — первые 100 человек со скидкой».",
    platform: "YouTube",
    city: "Astana",
    category: "Podkasty",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "8 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@medclinic_kz",
    contactWhatsapp: null,
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "autowash-astana@seed.kz",
    ownerName: "АвтоМойка Сам",
    companyName: "АвтоМойка Сам",
    title: "«Мы открыли мойку самообслуживания в Астане — снимай как моешь и получай за просмотры»",
    description: "Автомойка самообслуживания ищет автора YouTube Shorts. Хотим серию видео «Как правильно мыть машину зимой/летом/осенью» — обучающий формат от лица нашего технолога. Реальные советы, которые люди не знают. В конце: «Приезжай на нашу мойку — 5 постов, пенный пистолет, воск в комплекте». Нужен автор, умеющий снимать в условиях улицы.",
    platform: "YouTube",
    city: "Astana",
    category: "Avto",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@autowash_astana",
    contactWhatsapp: "+77015559900",
    boosts: ["premium"] as string[],
    featured: true,
  },
] as const;
