/**
 * Объявления 51–100 (вторая половина)
 * budgetType: "per_views" — оплата за просмотры в milestone-формате
 */

export const ADS_DATA_2 = [
  {
    ownerEmail: "shymkent-flowers@seed.kz",
    ownerName: "Shymkent Flowers",
    companyName: "Shymkent Flowers",
    title: "«Какие цветы живут дольше всего — проверяем 7 букетов за 14 дней» — Reels",
    description: "Цветочный магазин ищет автора Reels. Честный эксперимент — покупаем 7 разных букетов, ставим в одинаковые условия, снимаем каждый день. В финале: «Наши цветы с обработкой — стоят на 5 дней дольше».",
    platform: "Instagram",
    city: "Shymkent",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "2 500 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@shymkent_flowers",
    contactWhatsapp: "+77714445566",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "karaganda-gym@seed.kz",
    ownerName: "Karaganda Gym Pro",
    companyName: "Karaganda Gym Pro",
    title: "«Мы взяли человека без спортивного прошлого и тренировали 3 месяца — вот результат с цифрами»",
    description: "Фитнес-клуб ищет автора TikTok. Документальный дневник трансформации реального клиента. Начинаем с замеров — вес, жир, мышцы. Снимаем каждые 2 недели. В конце — честные цифры. В финале: «Первая консультация бесплатно».",
    platform: "TikTok",
    city: "Karaganda",
    category: "Sport",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@karaganda_gym_pro",
    contactWhatsapp: "+77212334455",
    boosts: ["rise"] as string[],
    featured: false,
  },
  {
    ownerEmail: "astana-nails@seed.kz",
    ownerName: "Astana Nails",
    companyName: "Astana Nails",
    title: "«Почему гель-лак держится у одной клиентки 4 недели, а у другой — 5 дней» — TikTok",
    description: "Студия маникюра ищет автора TikTok. Мастер объясняет реальные причины разного результата — тип ногтей, уход дома, лампа, базовое покрытие. В финале: «Запишитесь — мы подберём уход под ваш тип ногтей».",
    platform: "TikTok",
    city: "Astana",
    category: "Krasota",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@astana_nails",
    contactWhatsapp: "+77013335566",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "playonline@seed.kz",
    ownerName: "Play Online Games",
    companyName: "Play Online Games",
    title: "«Сколько часов в день тратят казахстанцы на видеоигры — и это норма или нет» — YouTube Shorts",
    description: "Игровая платформа ищет автора YouTube Shorts. Берём статистику игрового времени казахстанцев, сравниваем с Кореей и Японией, разбираем с психологом. В финале: «У нас — безопасная игровая среда с родительским контролем».",
    platform: "YouTube",
    city: "Almaty",
    category: "Geympley",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@playonline_kz",
    contactWhatsapp: null,
    boosts: ["vip"] as string[],
    featured: false,
  },
  {
    ownerEmail: "art-picasso@seed.kz",
    ownerName: "Арт-студия Пикассо",
    companyName: "Арт-студия Пикассо",
    title: "«Художник рисовал 30 минут в день — вот что получилось через год» — Reels для арт-студии",
    description: "Студия рисования ищет автора Reels. Таймлапс прогресса реального ученика — с первого занятия до финальной работы. В финале: «Запись на пробный урок — первое занятие бесплатно».",
    platform: "Instagram",
    city: "Almaty",
    category: "MuzykaAtmosfera",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@art_picasso_kz",
    contactWhatsapp: "+77012226677",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "foodtruck-almaty@seed.kz",
    ownerName: "FoodTruck Almaty",
    companyName: "FoodTruck Almaty",
    title: "«Мы готовим шаурму прямо на улице Алматы — покажи нашу кухню и заработай» — TikTok",
    description: "Фудтрак ищет автора TikTok. Формат: показываем весь процесс приготовления шаурмы — мясо на шпажке, свежие овощи, соус. Без скрытого, без постановки. В конце: «Мы стоим каждый день с 11 до 22 на [адрес] — приходи попробовать». Нужен автор, умеющий снимать на улице при любой погоде.",
    platform: "TikTok",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@foodtruck_almaty",
    contactWhatsapp: "+77011115566",
    boosts: ["premium"] as string[],
    featured: false,
  },
  {
    ownerEmail: "astana-marathon@seed.kz",
    ownerName: "Astana Marathon",
    companyName: "Astana Marathon",
    title: "«Этот человек пробежал первый марафон в 52 года — вот как он готовился 8 месяцев»",
    description: "Марафонский клуб ищет автора Instagram. Документальная история реального участника — его путь от дивана до финишной черты. В финале: «Наш клуб поможет тебе начать — первая тренировка бесплатно».",
    platform: "Instagram",
    city: "Astana",
    category: "Sport",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "6 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@astana_marathon",
    contactWhatsapp: "+77014447788",
    boosts: [] as string[],
    featured: true,
  },
  {
    ownerEmail: "astana-opera@seed.kz",
    ownerName: "Astana Opera",
    companyName: "Astana Opera",
    title: "«За сценой Астана Опера — что происходит за 2 часа до спектакля» — Reels с закулисьем",
    description: "Оперный театр ищет автора Instagram. Показываем что обычно скрыто: грим-артисты за работой, певцы на распевке, технический персонал. В финале: «Билеты на ноябрьскую премьеру — по ссылке».",
    platform: "Instagram",
    city: "Astana",
    category: "MuzykaAtmosfera",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@astana_opera_media",
    contactWhatsapp: null,
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "surf-kz@seed.kz",
    ownerName: "Surf KZ",
    companyName: "Surf KZ",
    title: "«Новичок vs. инструктор: кто первым встанет на доску» — TikTok для школы кайтсерфинга",
    description: "Школа кайтсерфинга ищет автора TikTok. Документируем первый урок человека без опыта — с юмором и честностью. Показываем реальные падения, первый подъём. В финале: «Запишись на пробный урок — в октябре последние места».",
    platform: "TikTok",
    city: "Aktau",
    category: "Sport",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@surf_kz",
    contactWhatsapp: "+77292224455",
    boosts: ["rise"] as string[],
    featured: false,
  },
  {
    ownerEmail: "qazaq-moda@seed.kz",
    ownerName: "Qazaq Moda",
    companyName: "Qazaq Moda",
    title: "«Мы сравнили казахский и турецкий ткань одного артикула — вот что оказалось» — YouTube Shorts",
    description: "Казахстанский фешн-бренд ищет автора YouTube. Берём ткань казахского и турецкого производства — тестируем плотность, износостойкость, цвет после стирки. В финале: «Наша коллекция из казахстанских тканей — сейчас со скидкой 20%».",
    platform: "YouTube",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "8 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@qazaq_moda",
    contactWhatsapp: "+77013338899",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "pavlodar-kids@seed.kz",
    ownerName: "Pavlodar Kids",
    companyName: "Pavlodar Kids",
    title: "«Мы дали 5-летнему ребёнку 30 минут свободного времени — вот что он выбрал сам» — Reels",
    description: "Детский центр в Павлодаре ищет автора Reels. Эксперимент: даём ребёнку выбор — планшет, краски или конструктор. В финале: «У нас — среда, где дети сами выбирают как развиваться».",
    platform: "Instagram",
    city: "Pavlodar",
    category: "Multfilmy",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@pavlodar_kids",
    contactWhatsapp: "+77181119900",
    boosts: ["vip"] as string[],
    featured: false,
  },
  {
    ownerEmail: "zhailu-dom@seed.kz",
    ownerName: "Жайлы Дом",
    companyName: "Жайлы Дом",
    title: "«Что скрывают застройщики в договоре долевого участия — юрист разбирает 10 пунктов»",
    description: "Застройщик ищет автора YouTube Shorts. Юрист разбирает типичные хитрости в договорах недвижимости — мы одни из немногих, кто этим не занимается. В финале: «Сравните наш договор — он открыт на сайте».",
    platform: "YouTube",
    city: "Almaty",
    category: "Podkasty",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "8 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@zhailu_dom",
    contactWhatsapp: "+77014441122",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "estetik-almaty@seed.kz",
    ownerName: "Эстетик Кабинет",
    companyName: "Эстетик Кабинет",
    title: "«Косметолог честно о том, что работает, а что нет — 5 процедур под проверку» — YouTube Shorts",
    description: "Кабинет эстетической косметологии ищет автора YouTube Shorts. Косметолог в кадре честно отвечает: что из популярных процедур реально работает, а что — маркетинг. Образовательный контент, вызывающий доверие. В финале: «Запишитесь на консультацию — бесплатно». Нужен автор с умением работать со специалистом на камере.",
    platform: "YouTube",
    city: "Almaty",
    category: "Krasota",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@estetik_almaty",
    contactWhatsapp: "+77011223355",
    boosts: ["premium"] as string[],
    featured: false,
  },
  {
    ownerEmail: "kofe-ray@seed.kz",
    ownerName: "Кофе Рай",
    companyName: "Кофе Рай",
    title: "«Мы сравнили кофе за 500 ₸ и за 2000 ₸ — слепой тест с 10 случайными людьми» — Reels",
    description: "Уютная кофейня ищет автора Instagram. Слепой тест нашего кофе и кофе конкурентов без этикеток. Честный результат. В финале: «Приди и проверь сам — первый кофе за 1 ₸ в день открытия».",
    platform: "Instagram",
    city: "Shymkent",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "2 500 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@kofe_ray_shymkent",
    contactWhatsapp: "+77712228899",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "almaty-fc@seed.kz",
    ownerName: "Almaty FC",
    companyName: "Almaty FC",
    title: "«Сколько зарабатывает футболист в казахстанской Премьер-лиге» — TikTok-эксклюзив",
    description: "Футбольный клуб Алматы ищет автора TikTok. Откровенные интервью с игроками — реальная жизнь казахстанского профессионального футбола. В финале: «Приходи на следующий матч — билеты по акции».",
    platform: "TikTok",
    city: "Almaty",
    category: "Sport",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "7 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@almaty_fc_media",
    contactWhatsapp: "+77011117788",
    boosts: ["rise"] as string[],
    featured: true,
  },
  {
    ownerEmail: "bookstore-kz@seed.kz",
    ownerName: "BookStore KZ",
    companyName: "BookStore KZ",
    title: "«Книга, которую читают все казахстанские предприниматели — проверяем каждый совет»",
    description: "Книжный магазин ищет автора TikTok. Берём бестселлер и проверяем каждый совет в реальной жизни. В финале: «Книга у нас — с доставкой по Казахстану».",
    platform: "TikTok",
    city: "Almaty",
    category: "Podkasty",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@bookstore_kz",
    contactWhatsapp: "+77012229900",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "ecowear@seed.kz",
    ownerName: "EcoWear KZ",
    companyName: "EcoWear KZ",
    title: "«Мы показали алматинке её гардероб с точки зрения экологии — вот что она обнаружила»",
    description: "Бренд экологичной одежды ищет автора Instagram. Реальный аудит гардероба — сколько вещей не надевалось больше года. В финале: «Мы принимаем старые вещи и отдаём скидку на новые».",
    platform: "Instagram",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "8 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@ecowear_kz",
    contactWhatsapp: "+77013331144",
    boosts: ["vip"] as string[],
    featured: false,
  },
  {
    ownerEmail: "aktau-fish@seed.kz",
    ownerName: "Aktau Fresh Market",
    companyName: "Aktau Fresh Market",
    title: "«Рыбак из Актау поймал 50 кг рыбы за день — вот как и где» — TikTok",
    description: "Рынок свежей рыбы ищет автора TikTok. Документируем выход рыбаков с раннего утра — реальная рыбалка на Каспии. В финале: «Закажи свежую рыбу с доставкой — рубка и упаковка бесплатно».",
    platform: "TikTok",
    city: "Aktau",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@aktau_fish_market",
    contactWhatsapp: "+77291115566",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "kaspi-seller-kz@seed.kz",
    ownerName: "Kaspi Seller KZ",
    companyName: "Kaspi Seller KZ",
    title: "«Я продаю на Kaspi магазине 2 года — вот сколько зарабатываю и как начать с нуля» — TikTok",
    description: "Онлайн-школа для продавцов на маркетплейсах ищет автора TikTok. Формат: реальный предприниматель показывает свою витрину на Kaspi, рассказывает сколько продаж в месяц, как выбирал нишу. В конце: «Хочешь так же? Запишись на наш курс — первый урок бесплатно». Нужен автор, умеющий снимать скрины и интерфейсы понятно.",
    platform: "TikTok",
    city: "Almaty",
    category: "Podkasty",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@kaspi_seller_kz",
    contactWhatsapp: "+77011339900",
    boosts: ["premium"] as string[],
    featured: false,
  },
  {
    ownerEmail: "karaganda-craft@seed.kz",
    ownerName: "Karaganda Craft",
    companyName: "Karaganda Craft",
    title: "«Мы варили продукт 48 часов — вот каждый этап изнутри» — YouTube для мастерской",
    description: "Крафтовая мастерская ищет автора YouTube Shorts. Документируем полный цикл создания продукта с объяснением каждого шага. В финале: «Дегустация в нашей мастерской — каждые 2 недели».",
    platform: "YouTube",
    city: "Karaganda",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@karaganda_craft",
    contactWhatsapp: "+77212226677",
    boosts: ["rise"] as string[],
    featured: false,
  },
  {
    ownerEmail: "almaty-tattoo@seed.kz",
    ownerName: "Almaty Tattoo",
    companyName: "Almaty Tattoo",
    title: "«Художница делала тату 8 лет — вот как изменились её первые работы» — Reels",
    description: "Тату-студия ищет автора Reels. Сравниваем первые и нынешние работы мастера год за годом. В финале: «Запишись к нам — первая консультация бесплатно».",
    platform: "Instagram",
    city: "Almaty",
    category: "Krasota",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 500 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@almaty_tattoo_art",
    contactWhatsapp: "+77011118899",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "qazaq-nomads@seed.kz",
    ownerName: "Qazaq Nomads Agency",
    companyName: "Qazaq Nomads Agency",
    title: "«7 дней в горах без телефона — вот что изменилось в голове» — YouTube документалка",
    description: "Тур-агентство ищет автора YouTube. Документируем реальный опыт человека без смартфона в горном туре. В финале: «Следующий тур в ноябре — последние 2 места».",
    platform: "YouTube",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "7 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@qazaq_nomads_tour",
    contactWhatsapp: "+77012227788",
    boosts: [] as string[],
    featured: true,
  },
  {
    ownerEmail: "astana-foodcourt@seed.kz",
    ownerName: "Astana Food Court",
    companyName: "Astana Food Court",
    title: "«Мы спросили 50 посетителей фудкорта: что они едят и сколько тратят» — TikTok",
    description: "Фудкорт ищет автора TikTok. Уличные мини-интервью — люди рассказывают о своём выборе. В финале: «Среди тех, кто отметит нас — розыгрыш сертификата на 5000 ₸ каждую неделю».",
    platform: "TikTok",
    city: "Astana",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@astana_foodcourt",
    contactWhatsapp: "+77014449900",
    boosts: ["vip"] as string[],
    featured: false,
  },
  {
    ownerEmail: "language-school@seed.kz",
    ownerName: "LanguageSchool KZ",
    companyName: "LanguageSchool KZ",
    title: "«Казахстанец выучил английский за 6 месяцев с нуля — вот его метод»",
    description: "Языковая школа ищет автора YouTube Shorts. Документируем реальный прогресс ученика. Каждый месяц — тест на уровень, реальный разговор с носителем. В финале: «Первые 2 недели бесплатно».",
    platform: "YouTube",
    city: "Almaty",
    category: "Podkasty",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "6 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@language_school_kz",
    contactWhatsapp: "+77013334455",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "shinomontazh-almaty@seed.kz",
    ownerName: "Шиномонтаж Быстро",
    companyName: "Шиномонтаж Быстро",
    title: "«Механик объясняет: как понять что пора менять резину — 4 признака которые все игнорируют»",
    description: "Сеть шиномонтажных мастерских ищет автора TikTok. Мастер в кадре показывает реальный износ резины клиентов — с объяснением когда критично, а когда ещё можно ездить. Полезный контент, который люди сохраняют. В финале: «Переобуй шины у нас — без записи, за 30 минут». Нужен автор, умеющий снимать на производстве.",
    platform: "TikTok",
    city: "Almaty",
    category: "Avto",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@shinomontazh_bystro",
    contactWhatsapp: "+77011445500",
    boosts: ["premium"] as string[],
    featured: false,
  },
  {
    ownerEmail: "qazaq-barista@seed.kz",
    ownerName: "Qazaq Barista",
    companyName: "Qazaq Barista",
    title: "«Бариста с 10-летним опытом объясняет: почему ваш кофе дома не такой, как в кофейне»",
    description: "Сеть кофеен ищет автора YouTube Shorts. Бариста разбирает типичные ошибки домашней варки — помол, температура, тампинг. В финале: «Устали от экспериментов? Приходи к нам».",
    platform: "YouTube",
    city: "Almaty",
    category: "MuzykaAtmosfera",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@qazaq_barista",
    contactWhatsapp: "+77011223344",
    boosts: ["rise"] as string[],
    featured: false,
  },
  {
    ownerEmail: "shymkent-autoshow@seed.kz",
    ownerName: "Shymkent Auto Show",
    companyName: "Shymkent Auto Show",
    title: "«Самые редкие машины Казахстана — мы нашли их в Шымкенте» — TikTok для автошоу",
    description: "Автошоу ищет автора TikTok. До мероприятия едем по городу и снимаем интересные экземпляры авто с историей и интервью владельца. В финале: «Билеты на шоу — первые 50 по специальной цене».",
    platform: "TikTok",
    city: "Shymkent",
    category: "Avto",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "6 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@shymkent_autoshow",
    contactWhatsapp: "+77713337788",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "almaty-fashion@seed.kz",
    ownerName: "Almaty Fashion Week",
    companyName: "Almaty Fashion Week",
    title: "«Сколько стоит одно дефиле — мы посчитали бюджет показа мод Алматы» — Reels изнутри",
    description: "Организаторы недели моды ищут автора Instagram. Прозрачный взгляд на организацию большого ивента — декорации, кастинг, свет, звук. В финале: «Билеты на показ — по ссылке».",
    platform: "Instagram",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "7 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@almaty_fashion_week",
    contactWhatsapp: "+77012230000",
    boosts: ["vip"] as string[],
    featured: true,
  },
  {
    ownerEmail: "astana-itpark@seed.kz",
    ownerName: "Astana IT Park",
    companyName: "Astana IT Park",
    title: "«Этот стартапер получил $100 000 инвестиций в 23 года — вот что он сделал правильно»",
    description: "IT-парк Астаны ищет автора YouTube. Интервью с резидентами — молодыми основателями, которые получили финансирование. В финале: «Мы принимаем заявки на следующий поток резидентов».",
    platform: "YouTube",
    city: "Astana",
    category: "Podkasty",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "10 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@astana_it_park",
    contactWhatsapp: null,
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "sutochnoe-aktau@seed.kz",
    ownerName: "Посуточно Актау",
    companyName: "Посуточно Актау",
    title: "«Мы сдаём квартиру посуточно 3 года — вот сколько зарабатываем и с чего начали» — YouTube",
    description: "Хост посуточной аренды квартир ищет автора YouTube Shorts. Реальный разбор: сколько стоит подготовить квартиру, какие расходы, сколько в итоге зарабатываю за месяц. Честные цифры без прикрас. В конце: «Хотите сдавать через нас — возьмём квартиру в управление». Нужен автор с пониманием формата «деньги и бизнес».",
    platform: "YouTube",
    city: "Aktau",
    category: "Podkasty",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@sutochnoe_aktau",
    contactWhatsapp: "+77291234567",
    boosts: ["premium"] as string[],
    featured: false,
  },
  {
    ownerEmail: "shymkent-parfum@seed.kz",
    ownerName: "Шымкент Парфюм",
    companyName: "Шымкент Парфюм",
    title: "«Почему дорогой парфюм пахнет иначе через час — химик объясняет» — Reels",
    description: "Магазин парфюмерии ищет автора Instagram. Парфюмер объясняет состав аромата — ноты, испарение, реакция с кожей. В финале: «Попробуй наш ассортимент стойких ароматов — тестирование бесплатно».",
    platform: "Instagram",
    city: "Shymkent",
    category: "Krasota",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@shymkent_parfum",
    contactWhatsapp: "+77715551122",
    boosts: ["rise"] as string[],
    featured: false,
  },
  {
    ownerEmail: "pavlodar-music@seed.kz",
    ownerName: "Pavlodar Live Music",
    companyName: "Pavlodar Live Music",
    title: "«Этот музыкант играет в Павлодаре 15 лет и отказался переехать в Алматы — почему»",
    description: "Ресторан с живой музыкой ищет автора TikTok. История музыканта, выбравшего региональный путь. В финале: «Приходи послушать его живьём в эту пятницу».",
    platform: "TikTok",
    city: "Pavlodar",
    category: "MuzykaAtmosfera",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 500 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@pavlodar_live_music",
    contactWhatsapp: "+77185559900",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "almatygym-elite@seed.kz",
    ownerName: "AlmatyGym Elite",
    companyName: "AlmatyGym Elite",
    title: "«Руководитель компании тренируется в 5 утра — вот что это ему даёт» — Instagram",
    description: "Премиум-фитнес-клуб ищет автора Instagram. Следим за реальным топ-менеджером на тренировке — как физическая форма влияет на решения. В финале: «Попробуй утреннюю тренировку — первая неделя бесплатно».",
    platform: "Instagram",
    city: "Almaty",
    category: "Sport",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "7 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@almaty_gym_elite",
    contactWhatsapp: "+77011220033",
    boosts: ["vip"] as string[],
    featured: false,
  },
  {
    ownerEmail: "karaganda-bakery@seed.kz",
    ownerName: "Karaganda Bakery",
    companyName: "Karaganda Bakery",
    title: "«Мы печём хлеб каждые 4 часа — вот почему он не чёрствеет» — TikTok",
    description: "Пекарня ищет автора TikTok. Показываем производственный цикл честно — мука, опара, выпечка, температура. В финале: «Закажи с доставкой — прямо из печи».",
    platform: "TikTok",
    city: "Karaganda",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "2 500 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@karaganda_bakery",
    contactWhatsapp: "+77218882233",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "kurer-astana@seed.kz",
    ownerName: "КурьерАстана",
    companyName: "КурьерАстана",
    title: "«Курьер проехал за день 80 км по Астане — вот как выглядит его рабочий день» — Instagram-влог",
    description: "Локальный курьерский сервис ищет автора Instagram Reels. Следуем за курьером весь рабочий день — реальные заказы, реальные клиенты, реальные трудности и кайфы работы. Человечный контент, который люди смотрят до конца. В конце: «Хочешь быстрой доставки по Астане — мы работаем 7 дней, заказ через WhatsApp». Нужен автор, умеющий снимать на ходу.",
    platform: "Instagram",
    city: "Astana",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@kurer_astana",
    contactWhatsapp: "+77015550099",
    boosts: ["premium"] as string[],
    featured: true,
  },
  {
    ownerEmail: "aktau-surf@seed.kz",
    ownerName: "Aktau Surf House",
    companyName: "Aktau Surf House",
    title: "«Новичок vs. опытный: кто быстрее научится виндсерфингу на Каспии» — YouTube-эксперимент",
    description: "Школа виндсерфинга ищет автора YouTube. Берём людей разного возраста — 20 и 45 лет — с одинаковым курсом. В финале: «У нас учатся от 16 до 65 лет».",
    platform: "YouTube",
    city: "Aktau",
    category: "Sport",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "6 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@aktau_surf_house",
    contactWhatsapp: "+77294441122",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "smarthome@seed.kz",
    ownerName: "SmartHome KZ",
    companyName: "SmartHome KZ",
    title: "«Мы автоматизировали квартиру за 150 000 ₸ — вот что стало возможным» — TikTok",
    description: "Компания умных домов ищет автора TikTok. Берём квартиру клиента, устанавливаем систему, снимаем как изменилась жизнь через неделю. В финале: «Бесплатный замер и консультация по заявке».",
    platform: "TikTok",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "8 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@smarthome_kz",
    contactWhatsapp: "+77011229988",
    boosts: ["rise"] as string[],
    featured: false,
  },
  {
    ownerEmail: "almaty-zoo@seed.kz",
    ownerName: "Almaty Zoo",
    companyName: "Almaty Zoo",
    title: "«Почему животные в зоопарке живут дольше, чем в дикой природе» — TikTok с фактами",
    description: "Зоопарк ищет автора TikTok. Зоолог развеивает мифы о жизни животных в неволе с реальной статистикой. В финале: «Приходи познакомиться с нашими животными — каждые выходные».",
    platform: "TikTok",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@almaty_zoo",
    contactWhatsapp: "+77011221100",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "karaganda-cars@seed.kz",
    ownerName: "Karaganda Cars",
    companyName: "Karaganda Cars",
    title: "«Покупатель спросил продавца: вы сами ездите на таких машинах? — вот что он ответил» — YouTube",
    description: "Автодилер ищет автора YouTube Shorts. Откровенное интервью с менеджером — что они рекомендуют своим родственникам и на чём ездят сами. В финале: «Наши менеджеры ездят на тех же машинах, что продают».",
    platform: "YouTube",
    city: "Karaganda",
    category: "Avto",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "6 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@karaganda_cars",
    contactWhatsapp: "+77212227788",
    boosts: ["vip"] as string[],
    featured: false,
  },
  {
    ownerEmail: "aktau-yoga@seed.kz",
    ownerName: "Aktau Yoga",
    companyName: "Aktau Yoga",
    title: "«5 женщин практиковали йогу 21 день — вот что изменилось» — Reels для студии",
    description: "Йога-студия ищет автора Instagram. Групповой дневник трансформации 5 участниц с разной подготовкой — честно, без ретуши. В финале: «Следующий поток в ноябре — запись открыта».",
    platform: "Instagram",
    city: "Aktau",
    category: "Sport",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@aktau_yoga",
    contactWhatsapp: "+77291116677",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "ferma-almaty@seed.kz",
    ownerName: "Ферма Алатау",
    companyName: "Ферма Алатау",
    title: "«Фермер из-под Алматы рассказывает: почему супермаркетные овощи и фермерские — это разные вещи» — YouTube",
    description: "Небольшое тепличное хозяйство ищет автора YouTube Shorts. Фермер в кадре объясняет разницу между промышленным и фермерским выращиванием — почва, удобрения, сроки. Без агрессии, просто факты. В конце: «Наши овощи с доставкой по Алматы — заказывай на неделю». Нужен автор, умеющий снимать на природе, в теплицах.",
    platform: "YouTube",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@ferma_alatau",
    contactWhatsapp: "+77011778800",
    boosts: ["premium"] as string[],
    featured: false,
  },
  {
    ownerEmail: "shymkent-kino@seed.kz",
    ownerName: "Шымкент Кино",
    companyName: "Шымкент Кино",
    title: "«5 казахских фильмов, которые изменили отношение к нашей культуре — нарезки с разбором»",
    description: "Кинопроект ищет автора нарезок TikTok. Берём конкретные сцены из казахского кино, разбираем культурный контекст. В финале: «Мы снимаем новый казахский фильм — следи за проектом».",
    platform: "TikTok",
    city: "Shymkent",
    category: "KinoNarezki",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@shymkent_kino",
    contactWhatsapp: "+77712230011",
    boosts: ["rise"] as string[],
    featured: true,
  },
  {
    ownerEmail: "pavlodar-music-school@seed.kz",
    ownerName: "Pavlodar Music School",
    companyName: "Pavlodar Music School",
    title: "«Взрослый начал учиться игре на пианино в 40 лет — вот что получилось через 6 месяцев»",
    description: "Музыкальная школа в Павлодаре ищет автора Instagram. Документируем прогресс взрослого ученика без музыкального прошлого. В финале: «У нас группы для взрослых с нуля».",
    platform: "Instagram",
    city: "Pavlodar",
    category: "MuzykaAtmosfera",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@pavlodar_music_school",
    contactWhatsapp: "+77181115566",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "almaty-beauty-fair@seed.kz",
    ownerName: "Almaty Beauty Fair",
    companyName: "Almaty Beauty Fair",
    title: "«Сколько казахстанки тратят на косметику в месяц — мы спросили 100 человек»",
    description: "Выставка красоты ищет автора TikTok. Уличные интервью — люди рассказывают о своих расходах на красоту. В финале: «Приходи на нашу выставку — 200+ брендов в одном месте».",
    platform: "TikTok",
    city: "Almaty",
    category: "Krasota",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "10 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@almaty_beauty_fair",
    contactWhatsapp: "+77011234400",
    boosts: ["vip"] as string[],
    featured: false,
  },
  {
    ownerEmail: "karaganda-esports@seed.kz",
    ownerName: "Karaganda Esports",
    companyName: "Karaganda Esports",
    title: "«Казахстанец попал в международный киберспортивный турнир — как он тренировался 2 года»",
    description: "Организатор турниров ищет автора YouTube. Документалка о пути казахстанского киберспортсмена — сколько часов тренировался, от чего отказался. В финале: «У нас следующий отбор в январе».",
    platform: "YouTube",
    city: "Karaganda",
    category: "Geympley",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@karaganda_esports",
    contactWhatsapp: "+77212228899",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "cctv-almaty@seed.kz",
    ownerName: "SmartGuard Almaty",
    companyName: "SmartGuard Almaty",
    title: "«Мы установили камеры в квартире клиента — вот что она увидела пока была в командировке» — YouTube",
    description: "Компания по установке систем видеонаблюдения ищет автора YouTube Shorts. Реальные кейсы клиентов — что удалось записать, как помогло. С согласия людей, без приватных деталей. В конце: «Бесплатный выезд и смета по вашей квартире». Нужен автор, умеющий работать с реальными историями.",
    platform: "YouTube",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@smartguard_almaty",
    contactWhatsapp: "+77011556600",
    boosts: ["premium"] as string[],
    featured: false,
  },
  {
    ownerEmail: "aktau-business@seed.kz",
    ownerName: "Aktau Business Club",
    companyName: "Aktau Business Club",
    title: "«Предприниматель из Актау зарабатывает больше алматинского ровесника — вот как»",
    description: "Бизнес-клуб Актау ищет ведущего для YouTube-подкаста. Разрушаем миф, что деньги только в столицах. Интервью с предпринимателями Мангистауской области с реальными цифрами.",
    platform: "YouTube",
    city: "Aktau",
    category: "Podkasty",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "5 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@aktau_business_club",
    contactWhatsapp: "+77291117788",
    boosts: ["rise"] as string[],
    featured: false,
  },
  {
    ownerEmail: "astana-barber@seed.kz",
    ownerName: "Astana Barbershop",
    companyName: "Astana Barbershop",
    title: "«Мастер делает одну стрижку 45 минут — вот почему это стоит дороже, чем везде» — TikTok",
    description: "Сеть барбершопов ищет автора TikTok. Показываем каждый этап стрижки с объяснением — зачем каждый инструмент, почему именно такие техники. В финале: «Запись на стрижку — по ссылке».",
    platform: "TikTok",
    city: "Astana",
    category: "Krasota",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 500 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@astana_barbershop",
    contactWhatsapp: "+77014443300",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "shymkent-food-market@seed.kz",
    ownerName: "Shymkent Food Market",
    companyName: "Shymkent Food Market",
    title: "«Что едят шымкентцы на завтрак — мы спросили 50 человек на рынке» — TikTok",
    description: "Фудмаркет ищет автора TikTok. Уличные мини-интервью на рынке — люди показывают что купили и рассказывают почему. В финале: «Приходи к нам — здесь всё это в одном месте».",
    platform: "TikTok",
    city: "Shymkent",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "4 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@shymkent_food_market",
    contactWhatsapp: "+77712234455",
    boosts: ["vip"] as string[],
    featured: false,
  },
  {
    ownerEmail: "pavlodar-animators@seed.kz",
    ownerName: "Pavlodar Animators",
    companyName: "Pavlodar Animators",
    title: "«Мем, который понятен только павлодарцам — создаём серию локальных видео»",
    description: "Студия анимации ищет автора TikTok-мемов. Нужны видео про павлодарские реалии — местные события, погода, особенности города. Требование: знание города и местного контекста.",
    platform: "TikTok",
    city: "Pavlodar",
    category: "Memy",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "3 000 ₸ за каждые 50 000 просмотров",
    contactTelegram: "@pavlodar_animators",
    contactWhatsapp: "+77181113300",
    boosts: [] as string[],
    featured: false,
  },
  {
    ownerEmail: "almaty-city@seed.kz",
    ownerName: "Almaty City Media",
    companyName: "Almaty City",
    title: "«Как Алматы менялся последние 10 лет — документальный YouTube для города»",
    description: "Городской проект ищет автора YouTube. Документируем изменения в инфраструктуре, архитектуре, людях. Честный взгляд — и хорошее, и то что нужно сделать. Нужен автор с умением делать городскую документалистику.",
    platform: "YouTube",
    city: "Almaty",
    category: "Obzory",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "6 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@almaty_city_media",
    contactWhatsapp: null,
    boosts: ["premium"] as string[],
    featured: true,
  },
  {
    ownerEmail: "startuphub@seed.kz",
    ownerName: "StartupHub KZ",
    companyName: "StartupHub KZ",
    title: "«Этот казахстанский стартап провалился 3 раза — и на 4-й получил $500 000» — YouTube-подкаст",
    description: "Хаб для стартапов ищет автора YouTube-подкаста. Интервью с основателями, которые пережили несколько неудач. В финале: «У нас программа поддержки для стартапов на ранних стадиях».",
    platform: "YouTube",
    city: "Almaty",
    category: "Podkasty",
    budgetType: "per_views",
    budgetFrom: null,
    budgetTo: null,
    budgetDetails: "6 000 ₸ за каждые 100 000 просмотров",
    contactTelegram: "@startuphub_kz",
    contactWhatsapp: "+77012231122",
    boosts: [] as string[],
    featured: false,
  },
] as const;
