/**
 * Креаторские профили 1–28 (первая половина)
 * Каждый профиль — уникальный email, детальные данные, часть с бустами.
 */

export interface CreatorSeedItem {
  email: string;
  name: string;
  fullName: string;
  title: string;
  bio: string;
  city: string;
  age: number | null;
  availability: string;
  verified: boolean;
  categories: string[];
  platforms: { name: string; handle: string; url: string; followers: number }[];
  minimumRate: number;
  priceItems: { label: string; price: number; sortOrder: number }[];
  contactTelegram: string;
  contactWhatsapp: string | null;
  averageRating: number;
  reviewCount: number;
  boosts: string[];
}

export const CREATORS_DATA_1: CreatorSeedItem[] = [
  // ─── PREMIUM BOOST (3) ────────────────────────────────────────────────────
  {
    email: "asyl.kairbekova@creator-seed.kz",
    name: "Асыл Каирбекова",
    fullName: "Асыл Каирбекова",
    title: "Бьюти-блогер №1 Алматы",
    bio: "Делаю бьюти-контент для брендов: от GRWM до полноценных обзоров косметики. Работаю с L'Oréal, Maybelline, локальными марками. Средний ER на TikTok — 12%, охваты Reels от 80K. Умею подать продукт так, чтобы зрители сами спрашивали ссылку в комментариях.",
    city: "Almaty",
    age: 24,
    availability: "available",
    verified: true,
    categories: ["Krasota"],
    platforms: [
      { name: "TikTok", handle: "@asyl.beauty", url: "https://tiktok.com/@asyl.beauty", followers: 320000 },
      { name: "Instagram", handle: "@asyl_kairbekova", url: "https://instagram.com/asyl_kairbekova", followers: 180000 },
    ],
    minimumRate: 80000,
    priceItems: [
      { label: "TikTok GRWM с интеграцией", price: 80000, sortOrder: 0 },
      { label: "Instagram Reels обзор", price: 65000, sortOrder: 1 },
      { label: "Stories (серия 3 шт)", price: 35000, sortOrder: 2 },
      { label: "Комплекс TikTok + Reels", price: 120000, sortOrder: 3 },
    ],
    contactTelegram: "@asyl_beauty",
    contactWhatsapp: "+77051234501",
    averageRating: 4.9,
    reviewCount: 34,
    boosts: ["premium"],
  },
  {
    email: "ernar.toleuov@creator-seed.kz",
    name: "Ернар Толеуов",
    fullName: "Ернар Толеуов",
    title: "Автообзорщик Pro",
    bio: "Профессиональный автоблогер: тест-драйвы, разборы, сравнения. Снимал для Toyota KZ, Kolesa.kz, Shell Kazakhstan. YouTube — основной канал с длинными обзорами, TikTok — для вирусных нарезок. Собственная студия с освещением и стедикамом.",
    city: "Astana",
    age: 29,
    availability: "available",
    verified: true,
    categories: ["Avto", "Obzory"],
    platforms: [
      { name: "YouTube", handle: "@ernar_auto", url: "https://youtube.com/@ernar_auto", followers: 250000 },
      { name: "TikTok", handle: "@ernar.auto", url: "https://tiktok.com/@ernar.auto", followers: 120000 },
    ],
    minimumRate: 60000,
    priceItems: [
      { label: "YouTube полный обзор (5-10 мин)", price: 90000, sortOrder: 0 },
      { label: "YouTube Shorts тест-драйв", price: 40000, sortOrder: 1 },
      { label: "TikTok нарезка из обзора", price: 25000, sortOrder: 2 },
      { label: "Комплекс YouTube + TikTok", price: 110000, sortOrder: 3 },
    ],
    contactTelegram: "@ernar_auto_pro",
    contactWhatsapp: "+77071234502",
    averageRating: 4.8,
    reviewCount: 28,
    boosts: ["premium"],
  },
  {
    email: "diana.sagynbaeva@creator-seed.kz",
    name: "Диана Сагынбаева",
    fullName: "Диана Сагынбаева",
    title: "Лайфстайл и тренды",
    bio: "Создаю вирусный контент на стыке лайфстайла и трендов. Мои ролики набирают от 200K просмотров органически. Работала с Kaspi, Glovo, Wolt. Умею адаптировать бренд под трендовый формат так, чтобы это не выглядело рекламой. ER на TikTok — 14%.",
    city: "Almaty",
    age: 22,
    availability: "partially_available",
    verified: true,
    categories: ["Memy", "MuzykaAtmosfera"],
    platforms: [
      { name: "TikTok", handle: "@diana.trends", url: "https://tiktok.com/@diana.trends", followers: 400000 },
      { name: "Instagram", handle: "@diana_sagynbaeva", url: "https://instagram.com/diana_sagynbaeva", followers: 220000 },
    ],
    minimumRate: 100000,
    priceItems: [
      { label: "TikTok трендовый ролик", price: 100000, sortOrder: 0 },
      { label: "Instagram Reels + Stories", price: 85000, sortOrder: 1 },
      { label: "Серия из 3 TikTok", price: 250000, sortOrder: 2 },
    ],
    contactTelegram: "@diana_trends",
    contactWhatsapp: "+77081234503",
    averageRating: 5.0,
    reviewCount: 41,
    boosts: ["premium"],
  },

  // ─── VIP BOOST (4) ────────────────────────────────────────────────────────
  {
    email: "ruslan.bekmurzaev@creator-seed.kz",
    name: "Руслан Бекмурзаев",
    fullName: "Руслан Бекмурзаев",
    title: "Геймплей и стримы",
    bio: "Стример и контент-мейкер по играм: Valorant, CS2, Dota 2. Делаю хайлайты, мемные нарезки, обучающие ролики. Аудитория — 16-25 лет, мужская. Сотрудничал с Beeline Казахстан, Aviata, местными кибер-клубами. Средний просмотр клипа — 50K.",
    city: "Astana",
    age: 23,
    availability: "available",
    verified: false,
    categories: ["Geympley"],
    platforms: [
      { name: "TikTok", handle: "@ruslan_gamer", url: "https://tiktok.com/@ruslan_gamer", followers: 180000 },
      { name: "YouTube", handle: "@RuslanPlays", url: "https://youtube.com/@RuslanPlays", followers: 95000 },
    ],
    minimumRate: 35000,
    priceItems: [
      { label: "TikTok геймплей-ролик", price: 35000, sortOrder: 0 },
      { label: "YouTube хайлайт (3-5 мин)", price: 50000, sortOrder: 1 },
      { label: "Стрим-интеграция (1 час)", price: 80000, sortOrder: 2 },
    ],
    contactTelegram: "@ruslan_gamer",
    contactWhatsapp: "+77091234504",
    averageRating: 4.6,
    reviewCount: 19,
    boosts: ["vip"],
  },
  {
    email: "alina.zhumatova@creator-seed.kz",
    name: "Алина Жуматова",
    fullName: "Алина Жуматова",
    title: "Спортивный контент",
    bio: "Фитнес-блогер и персональный тренер. Снимаю тренировки, мотивационный контент, обзоры спортивного питания и экипировки. Работала с Nike Kazakhstan, MyProtein, FitCurves. Моя аудитория — девушки 20-35 лет, которые хотят быть в форме.",
    city: "Almaty",
    age: 26,
    availability: "available",
    verified: true,
    categories: ["Sport"],
    platforms: [
      { name: "Instagram", handle: "@alina.fit", url: "https://instagram.com/alina.fit", followers: 150000 },
      { name: "TikTok", handle: "@alina_fitness", url: "https://tiktok.com/@alina_fitness", followers: 80000 },
    ],
    minimumRate: 45000,
    priceItems: [
      { label: "Instagram Reels тренировка", price: 45000, sortOrder: 0 },
      { label: "TikTok фитнес-челлендж", price: 35000, sortOrder: 1 },
      { label: "Обзор продукта (Reels + Stories)", price: 60000, sortOrder: 2 },
    ],
    contactTelegram: "@alina_fitness",
    contactWhatsapp: "+77011234505",
    averageRating: 4.7,
    reviewCount: 22,
    boosts: ["vip"],
  },
  {
    email: "timur.kasenov@creator-seed.kz",
    name: "Тимур Касенов",
    fullName: "Тимур Касенов",
    title: "Нарезки из фильмов и сериалов",
    bio: "Специализируюсь на кинонарезках: монтирую эмоциональные, смешные и драматичные моменты из фильмов с текстом и музыкой. Мои ролики стабильно набирают 100-500K просмотров. Умею адаптировать рекламу под кинонарезку так, что зритель досматривает до конца. Работал с онлайн-кинотеатрами и стриминговыми сервисами.",
    city: "Almaty",
    age: 21,
    availability: "available",
    verified: false,
    categories: ["KinoNarezki"],
    platforms: [
      { name: "TikTok", handle: "@timur_cinema", url: "https://tiktok.com/@timur_cinema", followers: 250000 },
    ],
    minimumRate: 25000,
    priceItems: [
      { label: "TikTok кинонарезка с интеграцией", price: 25000, sortOrder: 0 },
      { label: "Серия из 3 нарезок", price: 60000, sortOrder: 1 },
      { label: "Брендированная нарезка (сценарий)", price: 40000, sortOrder: 2 },
    ],
    contactTelegram: "@timur_cinema",
    contactWhatsapp: null,
    averageRating: 4.5,
    reviewCount: 15,
    boosts: ["vip"],
  },
  {
    email: "kamila.nurgalieva@creator-seed.kz",
    name: "Камила Нургалиева",
    fullName: "Камила Нургалиева",
    title: "Подкасты и интервью",
    bio: "Веду подкаст о жизни и карьере в Казахстане. Формат: глубинные интервью с предпринимателями, экспертами, селебрити. Могу интегрировать бренд в тему выпуска, сделать отдельную рубрику или нативную рекомендацию. YouTube — основная площадка, Instagram — клипы и анонсы.",
    city: "Astana",
    age: 28,
    availability: "partially_available",
    verified: true,
    categories: ["Podkasty"],
    platforms: [
      { name: "YouTube", handle: "@kamila_podcast", url: "https://youtube.com/@kamila_podcast", followers: 120000 },
      { name: "Instagram", handle: "@kamila.podcast", url: "https://instagram.com/kamila.podcast", followers: 45000 },
    ],
    minimumRate: 50000,
    priceItems: [
      { label: "Интеграция в выпуск подкаста", price: 50000, sortOrder: 0 },
      { label: "Отдельная рубрика в выпуске", price: 80000, sortOrder: 1 },
      { label: "Instagram Reels анонс", price: 20000, sortOrder: 2 },
    ],
    contactTelegram: "@kamila_podcast",
    contactWhatsapp: "+77021234507",
    averageRating: 4.8,
    reviewCount: 12,
    boosts: ["vip"],
  },

  // ─── RISE BOOST (5) ───────────────────────────────────────────────────────
  {
    email: "arman.zhanserik@creator-seed.kz",
    name: "Арман Жансерик",
    fullName: "Арман Жансерик",
    title: "Мемы и юмор на казахском",
    bio: "Делаю мемный контент на казахском и русском языках. Мои ролики часто попадают в рекомендации — средний охват 80-200K. Умею адаптировать рекламу под юмористический формат: скетчи, пародии, мемные ситуации. Работал с Dodo Pizza, Choco, Air Astana.",
    city: "Shymkent",
    age: 20,
    availability: "available",
    verified: false,
    categories: ["Memy"],
    platforms: [
      { name: "TikTok", handle: "@arman_memes", url: "https://tiktok.com/@arman_memes", followers: 160000 },
      { name: "Instagram", handle: "@arman.memes", url: "https://instagram.com/arman.memes", followers: 42000 },
    ],
    minimumRate: 15000,
    priceItems: [
      { label: "TikTok мем с интеграцией", price: 15000, sortOrder: 0 },
      { label: "Instagram Reels скетч", price: 20000, sortOrder: 1 },
      { label: "Серия из 5 мемов", price: 60000, sortOrder: 2 },
    ],
    contactTelegram: "@arman_memes",
    contactWhatsapp: "+77031234508",
    averageRating: 4.3,
    reviewCount: 8,
    boosts: ["rise"],
  },
  {
    email: "madina.orazova@creator-seed.kz",
    name: "Мадина Оразова",
    fullName: "Мадина Оразова",
    title: "Обзоры еды и ресторанов",
    bio: "Фуд-блогер: обзоры ресторанов, кафе, стрит-фуда по всему Казахстану. Честные отзывы с красивой съёмкой. Мои рекомендации реально приводят людей — рестораны отмечают рост посещений на 20-30% после публикации. Снимаю на iPhone 15 Pro + DJI Stabilizer.",
    city: "Almaty",
    age: 25,
    availability: "available",
    verified: false,
    categories: ["Obzory"],
    platforms: [
      { name: "TikTok", handle: "@madina.food", url: "https://tiktok.com/@madina.food", followers: 95000 },
      { name: "Instagram", handle: "@madina_foodie", url: "https://instagram.com/madina_foodie", followers: 72000 },
    ],
    minimumRate: 20000,
    priceItems: [
      { label: "TikTok обзор заведения", price: 20000, sortOrder: 0 },
      { label: "Instagram Reels + Stories", price: 30000, sortOrder: 1 },
      { label: "Серия из 3 обзоров", price: 55000, sortOrder: 2 },
    ],
    contactTelegram: "@madina_food",
    contactWhatsapp: "+77041234509",
    averageRating: 4.4,
    reviewCount: 11,
    boosts: ["rise"],
  },
  {
    email: "nursultan.akhmetov@creator-seed.kz",
    name: "Нурсултан Ахметов",
    fullName: "Нурсултан Ахметов",
    title: "Мультфильмы и анимация",
    bio: "Создаю анимационные ролики и нарезки из мультфильмов для рекламы. Работаю в After Effects и Blender. Могу сделать 2D/3D анимацию для бренда, или смонтировать вирусную нарезку из популярных мультфильмов с интеграцией. Средний охват — 60-150K.",
    city: "Karaganda",
    age: 27,
    availability: "partially_available",
    verified: false,
    categories: ["Multfilmy"],
    platforms: [
      { name: "TikTok", handle: "@nursultan_anim", url: "https://tiktok.com/@nursultan_anim", followers: 70000 },
      { name: "YouTube", handle: "@NursultanAnimation", url: "https://youtube.com/@NursultanAnimation", followers: 28000 },
    ],
    minimumRate: 30000,
    priceItems: [
      { label: "TikTok анимационный ролик", price: 30000, sortOrder: 0 },
      { label: "2D анимация для бренда (30 сек)", price: 50000, sortOrder: 1 },
      { label: "YouTube анимированный обзор", price: 45000, sortOrder: 2 },
    ],
    contactTelegram: "@nursultan_anim",
    contactWhatsapp: null,
    averageRating: 4.2,
    reviewCount: 6,
    boosts: ["rise"],
  },
  {
    email: "asel.muratova@creator-seed.kz",
    name: "Асель Муратова",
    fullName: "Асель Муратова",
    title: "Музыка и атмосферные видео",
    bio: "Создаю атмосферный контент с музыкой: лоу-фай визуалы, кинематографичные городские видео, mood-контент для брендов. Мои ролики используют для фоновой атмосферы в кафе, магазинах, на мероприятиях. Работаю с ресторанами, отелями, fashion-брендами.",
    city: "Almaty",
    age: 23,
    availability: "available",
    verified: false,
    categories: ["MuzykaAtmosfera"],
    platforms: [
      { name: "TikTok", handle: "@asel.mood", url: "https://tiktok.com/@asel.mood", followers: 110000 },
      { name: "Instagram", handle: "@asel_vibes", url: "https://instagram.com/asel_vibes", followers: 55000 },
      { name: "YouTube", handle: "@AselMoodVideos", url: "https://youtube.com/@AselMoodVideos", followers: 18000 },
    ],
    minimumRate: 25000,
    priceItems: [
      { label: "TikTok атмосферный ролик", price: 25000, sortOrder: 0 },
      { label: "Instagram Reels mood-video", price: 30000, sortOrder: 1 },
      { label: "YouTube атмосферный фильм (3-5 мин)", price: 60000, sortOrder: 2 },
    ],
    contactTelegram: "@asel_mood",
    contactWhatsapp: "+77061234511",
    averageRating: 4.6,
    reviewCount: 9,
    boosts: ["rise"],
  },
  {
    email: "baurzhan.serik@creator-seed.kz",
    name: "Бауыржан Серик",
    fullName: "Бауыржан Серик",
    title: "Кино-нарезки и озвучка",
    bio: "Озвучиваю и монтирую нарезки из фильмов на казахском. Мой голос узнаваем — его используют мемные каналы и рекламные ролики. Могу сделать нарезку с озвучкой для рекламы: зритель смотрит интересный контент и ненавязчиво узнаёт о продукте.",
    city: "Aktau",
    age: 25,
    availability: "available",
    verified: false,
    categories: ["KinoNarezki", "Memy"],
    platforms: [
      { name: "TikTok", handle: "@baurzhan_voice", url: "https://tiktok.com/@baurzhan_voice", followers: 85000 },
    ],
    minimumRate: 12000,
    priceItems: [
      { label: "TikTok нарезка с озвучкой", price: 12000, sortOrder: 0 },
      { label: "Озвучка рекламного ролика", price: 20000, sortOrder: 1 },
      { label: "Серия из 5 нарезок", price: 50000, sortOrder: 2 },
    ],
    contactTelegram: "@baurzhan_voice",
    contactWhatsapp: "+77071234512",
    averageRating: 4.1,
    reviewCount: 5,
    boosts: ["rise"],
  },

  // ─── БЕЗ БУСТА ────────────────────────────────────────────────────────────
  {
    email: "zarina.yessenova@creator-seed.kz",
    name: "Зарина Есенова",
    fullName: "Зарина Есенова",
    title: "Бьюти и уход за кожей",
    bio: "Рассказываю о корейской косметике и уходовых рутинах. Мои обзоры помогают девушкам подобрать средства по типу кожи. Работаю с локальными beauty-магазинами и корейскими брендами, представленными в Казахстане.",
    city: "Almaty",
    age: 22,
    availability: "available",
    verified: false,
    categories: ["Krasota", "Obzory"],
    platforms: [
      { name: "TikTok", handle: "@zarina.skin", url: "https://tiktok.com/@zarina.skin", followers: 45000 },
      { name: "Instagram", handle: "@zarina_skincare", url: "https://instagram.com/zarina_skincare", followers: 32000 },
    ],
    minimumRate: 15000,
    priceItems: [
      { label: "TikTok обзор продукта", price: 15000, sortOrder: 0 },
      { label: "Instagram Reels рутина", price: 18000, sortOrder: 1 },
    ],
    contactTelegram: "@zarina_skin",
    contactWhatsapp: "+77081234513",
    averageRating: 4.3,
    reviewCount: 7,
    boosts: [],
  },
  {
    email: "daniyar.kurmangali@creator-seed.kz",
    name: "Данияр Курмангали",
    fullName: "Данияр Курмангали",
    title: "Авто-контент и тест-драйвы",
    bio: "Снимаю обзоры авто для обычных людей: без сложных терминов, с фокусом на практику. Показываю что реально важно при покупке б/у авто в Казахстане. Мои подписчики — мужчины 25-40 лет, которые выбирают машину.",
    city: "Astana",
    age: 31,
    availability: "available",
    verified: false,
    categories: ["Avto"],
    platforms: [
      { name: "YouTube", handle: "@daniyar_cars", url: "https://youtube.com/@daniyar_cars", followers: 42000 },
      { name: "TikTok", handle: "@daniyar.auto", url: "https://tiktok.com/@daniyar.auto", followers: 28000 },
    ],
    minimumRate: 20000,
    priceItems: [
      { label: "YouTube обзор авто (5-8 мин)", price: 35000, sortOrder: 0 },
      { label: "TikTok мини-обзор", price: 15000, sortOrder: 1 },
      { label: "YouTube Shorts", price: 12000, sortOrder: 2 },
    ],
    contactTelegram: "@daniyar_auto",
    contactWhatsapp: "+77091234514",
    averageRating: 4.0,
    reviewCount: 4,
    boosts: [],
  },
  {
    email: "aigul.baimenova@creator-seed.kz",
    name: "Айгуль Байменова",
    fullName: "Айгуль Байменова",
    title: "Мемы и вирусный контент",
    bio: "Создаю мемы и вирусные ролики, которые люди сами шерят в чаты. Формат: жизненные ситуации + юмор + продукт. Мои видео регулярно выходят в топ рекомендаций TikTok. Работала с Choco, Kaspi QR, Sulpak.",
    city: "Almaty",
    age: 21,
    availability: "available",
    verified: false,
    categories: ["Memy"],
    platforms: [
      { name: "TikTok", handle: "@aigul_memes", url: "https://tiktok.com/@aigul_memes", followers: 130000 },
    ],
    minimumRate: 18000,
    priceItems: [
      { label: "TikTok мемный ролик", price: 18000, sortOrder: 0 },
      { label: "Серия из 3 мемов", price: 45000, sortOrder: 1 },
    ],
    contactTelegram: "@aigul_memes",
    contactWhatsapp: null,
    averageRating: 0,
    reviewCount: 0,
    boosts: [],
  },
  {
    email: "marat.aitbaev@creator-seed.kz",
    name: "Марат Айтбаев",
    fullName: "Марат Айтбаев",
    title: "Подкасты о бизнесе",
    bio: "Веду подкаст «Бизнес по-казахски» — интервью с предпринимателями из разных городов. Формат: длинные интервью на YouTube + нарезки на TikTok. Могу интегрировать бренд как спонсора выпуска или сделать тематический выпуск.",
    city: "Astana",
    age: 33,
    availability: "partially_available",
    verified: false,
    categories: ["Podkasty", "Obzory"],
    platforms: [
      { name: "YouTube", handle: "@MaratBizPodcast", url: "https://youtube.com/@MaratBizPodcast", followers: 68000 },
      { name: "TikTok", handle: "@marat_biz", url: "https://tiktok.com/@marat_biz", followers: 35000 },
      { name: "Instagram", handle: "@marat.podcast", url: "https://instagram.com/marat.podcast", followers: 22000 },
    ],
    minimumRate: 40000,
    priceItems: [
      { label: "Спонсорство выпуска подкаста", price: 60000, sortOrder: 0 },
      { label: "Тематический выпуск под бренд", price: 100000, sortOrder: 1 },
      { label: "TikTok нарезка из выпуска", price: 15000, sortOrder: 2 },
    ],
    contactTelegram: "@marat_biz_podcast",
    contactWhatsapp: "+77011234516",
    averageRating: 4.5,
    reviewCount: 10,
    boosts: [],
  },
  {
    email: "aizhan.nurtasova@creator-seed.kz",
    name: "Айжан Нуртасова",
    fullName: "Айжан Нуртасова",
    title: "Спорт и ЗОЖ контент",
    bio: "Снимаю контент о здоровом образе жизни: бег, йога, правильное питание. Моя аудитория — активные девушки 22-35 лет. Могу сделать интеграцию спортивного питания, одежды, приложений для тренировок.",
    city: "Shymkent",
    age: 24,
    availability: "available",
    verified: false,
    categories: ["Sport"],
    platforms: [
      { name: "Instagram", handle: "@aizhan_zozh", url: "https://instagram.com/aizhan_zozh", followers: 55000 },
      { name: "TikTok", handle: "@aizhan.fit", url: "https://tiktok.com/@aizhan.fit", followers: 38000 },
    ],
    minimumRate: 15000,
    priceItems: [
      { label: "Instagram Reels тренировка", price: 20000, sortOrder: 0 },
      { label: "TikTok фитнес-контент", price: 15000, sortOrder: 1 },
      { label: "Stories обзор продукта", price: 10000, sortOrder: 2 },
    ],
    contactTelegram: "@aizhan_zozh",
    contactWhatsapp: "+77021234517",
    averageRating: 0,
    reviewCount: 0,
    boosts: [],
  },
  {
    email: "bekzat.orazbekov@creator-seed.kz",
    name: "Бекзат Оразбеков",
    fullName: "Бекзат Оразбеков",
    title: "Геймплей Brawl Stars и Roblox",
    bio: "Снимаю геймплей для молодой аудитории: Brawl Stars, Roblox, Minecraft. Мои подписчики — дети и подростки 10-16 лет. Идеальный канал для рекламы детских товаров, образовательных приложений, гаджетов.",
    city: "Karaganda",
    age: 19,
    availability: "available",
    verified: false,
    categories: ["Geympley"],
    platforms: [
      { name: "TikTok", handle: "@bekzat_gamer", url: "https://tiktok.com/@bekzat_gamer", followers: 92000 },
      { name: "YouTube", handle: "@BekzatGames", url: "https://youtube.com/@BekzatGames", followers: 47000 },
    ],
    minimumRate: 10000,
    priceItems: [
      { label: "TikTok геймплей-ролик", price: 10000, sortOrder: 0 },
      { label: "YouTube летсплей (10 мин)", price: 25000, sortOrder: 1 },
      { label: "Серия из 5 TikTok", price: 40000, sortOrder: 2 },
    ],
    contactTelegram: "@bekzat_games",
    contactWhatsapp: null,
    averageRating: 3.8,
    reviewCount: 3,
    boosts: [],
  },
  {
    email: "dinara.sultanova@creator-seed.kz",
    name: "Динара Султанова",
    fullName: "Динара Султанова",
    title: "Кинонарезки и эмоции",
    bio: "Монтирую эмоциональные нарезки из фильмов и сериалов: драма, romance, мотивация. Моя аудитория — девушки 18-28 лет, которые любят кино. Реклама встраивается нативно через текст на экране или голосовое сообщение в конце.",
    city: "Astana",
    age: 22,
    availability: "available",
    verified: false,
    categories: ["KinoNarezki"],
    platforms: [
      { name: "TikTok", handle: "@dinara_cinema", url: "https://tiktok.com/@dinara_cinema", followers: 175000 },
      { name: "Instagram", handle: "@dinara.clips", url: "https://instagram.com/dinara.clips", followers: 48000 },
    ],
    minimumRate: 20000,
    priceItems: [
      { label: "TikTok кинонарезка", price: 20000, sortOrder: 0 },
      { label: "Instagram Reels монтаж", price: 22000, sortOrder: 1 },
      { label: "Серия из 3 нарезок", price: 50000, sortOrder: 2 },
    ],
    contactTelegram: "@dinara_cinema",
    contactWhatsapp: "+77041234519",
    averageRating: 4.4,
    reviewCount: 13,
    boosts: [],
  },
  {
    email: "yerzhan.tulegenov@creator-seed.kz",
    name: "Ержан Тулегенов",
    fullName: "Ержан Тулегенов",
    title: "Обзоры техники и гаджетов",
    bio: "Обозреваю технику: смартфоны, ноутбуки, наушники, умные часы. Мой подход — сравнение «для обычных людей»: без спецификаций, с фокусом на повседневное использование. Работал с Samsung KZ, Xiaomi, Technodom.",
    city: "Almaty",
    age: 26,
    availability: "partially_available",
    verified: false,
    categories: ["Obzory"],
    platforms: [
      { name: "YouTube", handle: "@yerzhan_tech", url: "https://youtube.com/@yerzhan_tech", followers: 85000 },
      { name: "TikTok", handle: "@yerzhan.tech", url: "https://tiktok.com/@yerzhan.tech", followers: 62000 },
      { name: "Instagram", handle: "@yerzhan_gadgets", url: "https://instagram.com/yerzhan_gadgets", followers: 28000 },
    ],
    minimumRate: 30000,
    priceItems: [
      { label: "YouTube обзор гаджета (5-10 мин)", price: 50000, sortOrder: 0 },
      { label: "TikTok распаковка / мини-обзор", price: 20000, sortOrder: 1 },
      { label: "Комплекс YouTube + TikTok + Reels", price: 75000, sortOrder: 2 },
    ],
    contactTelegram: "@yerzhan_tech",
    contactWhatsapp: "+77051234520",
    averageRating: 4.6,
    reviewCount: 18,
    boosts: [],
  },
  {
    email: "saltanat.kenzhebayeva@creator-seed.kz",
    name: "Салтанат Кенжебаева",
    fullName: "Салтанат Кенжебаева",
    title: "Мода и стиль Казахстан",
    bio: "Fashion-блогер: разбираю образы, делаю подборки из казахстанских магазинов, снимаю try-on. Моя аудитория — стильные девушки, которые ищут что надеть. Работала с Zara KZ, H&M, DOSSO DOSSI, локальные дизайнеры.",
    city: "Almaty",
    age: 25,
    availability: "available",
    verified: true,
    categories: ["Krasota"],
    platforms: [
      { name: "Instagram", handle: "@saltanat.style", url: "https://instagram.com/saltanat.style", followers: 110000 },
      { name: "TikTok", handle: "@saltanat_fashion", url: "https://tiktok.com/@saltanat_fashion", followers: 75000 },
    ],
    minimumRate: 35000,
    priceItems: [
      { label: "Instagram Reels try-on", price: 35000, sortOrder: 0 },
      { label: "TikTok образ дня", price: 25000, sortOrder: 1 },
      { label: "Подборка из 5 образов", price: 80000, sortOrder: 2 },
    ],
    contactTelegram: "@saltanat_style",
    contactWhatsapp: "+77061234521",
    averageRating: 4.7,
    reviewCount: 16,
    boosts: [],
  },
  {
    email: "adil.serikbay@creator-seed.kz",
    name: "Адиль Серикбай",
    fullName: "Адиль Серикбай",
    title: "Мемы и скетчи",
    bio: "Снимаю скетчи и мемные ролики о жизни в Казахстане: бытовые ситуации, работа, отношения. Мой контент вирусится благодаря узнаваемости ситуаций. Аудитория — 18-30 лет, 60% мужчины. Подхожу для рекламы еды, приложений, сервисов.",
    city: "Shymkent",
    age: 23,
    availability: "available",
    verified: false,
    categories: ["Memy"],
    platforms: [
      { name: "TikTok", handle: "@adil_sketch", url: "https://tiktok.com/@adil_sketch", followers: 200000 },
      { name: "Instagram", handle: "@adil.sketch", url: "https://instagram.com/adil.sketch", followers: 65000 },
    ],
    minimumRate: 22000,
    priceItems: [
      { label: "TikTok скетч с интеграцией", price: 22000, sortOrder: 0 },
      { label: "Instagram Reels", price: 25000, sortOrder: 1 },
      { label: "Серия из 3 скетчей", price: 55000, sortOrder: 2 },
    ],
    contactTelegram: "@adil_sketch",
    contactWhatsapp: "+77071234522",
    averageRating: 0,
    reviewCount: 0,
    boosts: [],
  },
  {
    email: "almas.turganbayev@creator-seed.kz",
    name: "Алмас Турганбаев",
    fullName: "Алмас Турганбаев",
    title: "Авто-детейлинг контент",
    bio: "Снимаю процесс детейлинга: полировка, керамика, чистка салонов. ASMR-формат + результат «до/после». Мои ролики залетают в рекомендации из-за визуальной привлекательности процесса. Идеально для рекламы автосервисов, химии, аксессуаров.",
    city: "Pavlodar",
    age: 28,
    availability: "available",
    verified: false,
    categories: ["Avto"],
    platforms: [
      { name: "TikTok", handle: "@almas_detail", url: "https://tiktok.com/@almas_detail", followers: 58000 },
      { name: "Instagram", handle: "@almas.detailing", url: "https://instagram.com/almas.detailing", followers: 22000 },
    ],
    minimumRate: 12000,
    priceItems: [
      { label: "TikTok ASMR детейлинг", price: 12000, sortOrder: 0 },
      { label: "Instagram Reels до/после", price: 15000, sortOrder: 1 },
    ],
    contactTelegram: "@almas_detail",
    contactWhatsapp: "+77081234523",
    averageRating: 0,
    reviewCount: 0,
    boosts: [],
  },
  {
    email: "zhanna.ospanova@creator-seed.kz",
    name: "Жанна Оспанова",
    fullName: "Жанна Оспанова",
    title: "Кинонарезки драма и romance",
    bio: "Специализируюсь на нарезках из турецких, корейских сериалов и казахстанского кино. Мои ролики собирают аудиторию женщин 20-40 лет. Могу встроить рекламу нативно: через текстовый overlay, через «рекомендацию от героя».",
    city: "Shymkent",
    age: 24,
    availability: "available",
    verified: false,
    categories: ["KinoNarezki"],
    platforms: [
      { name: "TikTok", handle: "@zhanna_drama", url: "https://tiktok.com/@zhanna_drama", followers: 140000 },
      { name: "Instagram", handle: "@zhanna.clips", url: "https://instagram.com/zhanna.clips", followers: 35000 },
    ],
    minimumRate: 16000,
    priceItems: [
      { label: "TikTok нарезка с интеграцией", price: 16000, sortOrder: 0 },
      { label: "Серия из 5 нарезок", price: 65000, sortOrder: 1 },
    ],
    contactTelegram: "@zhanna_drama",
    contactWhatsapp: "+77091234524",
    averageRating: 4.2,
    reviewCount: 9,
    boosts: [],
  },
  {
    email: "talgat.nurpeisov@creator-seed.kz",
    name: "Талгат Нурпеисов",
    fullName: "Талгат Нурпеисов",
    title: "Обзоры авто из Кореи",
    bio: "Обозреваю авто привезённые из Кореи: состояние, цены, подводные камни. Честный контент для тех, кто планирует покупку. YouTube — основная площадка с полными обзорами, TikTok — для быстрых советов.",
    city: "Almaty",
    age: 30,
    availability: "busy",
    verified: false,
    categories: ["Avto", "Obzory"],
    platforms: [
      { name: "YouTube", handle: "@talgat_avto", url: "https://youtube.com/@talgat_avto", followers: 55000 },
      { name: "TikTok", handle: "@talgat.korea.auto", url: "https://tiktok.com/@talgat.korea.auto", followers: 32000 },
    ],
    minimumRate: 25000,
    priceItems: [
      { label: "YouTube обзор авто из Кореи", price: 40000, sortOrder: 0 },
      { label: "TikTok мини-обзор", price: 15000, sortOrder: 1 },
      { label: "Сравнение 2 моделей", price: 55000, sortOrder: 2 },
    ],
    contactTelegram: "@talgat_avto",
    contactWhatsapp: "+77011234525",
    averageRating: 4.1,
    reviewCount: 6,
    boosts: [],
  },
];
