/**
 * Креаторские профили 29–55 (вторая половина)
 */

import type { CreatorSeedItem } from "./creators-data-1";

export const CREATORS_DATA_2: CreatorSeedItem[] = [
  {
    email: "nurzhan.alimov@creator-seed.kz",
    name: "Нуржан Алимов",
    fullName: "Нуржан Алимов",
    title: "Кинонарезки action и триллер",
    bio: "Монтирую динамичные нарезки из боевиков, триллеров, Marvel/DC. Мои ролики — это адреналин за 30 секунд. Аудитория — мужчины 16-30 лет. Интеграция через текст на экране или закадровый голос.",
    city: "Astana",
    age: 20,
    availability: "available",
    verified: false,
    categories: ["KinoNarezki"],
    platforms: [
      { name: "TikTok", handle: "@nurzhan_action", url: "https://tiktok.com/@nurzhan_action", followers: 115000 },
    ],
    minimumRate: 14000,
    priceItems: [
      { label: "TikTok action-нарезка", price: 14000, sortOrder: 0 },
      { label: "Серия из 3 нарезок", price: 35000, sortOrder: 1 },
    ],
    contactTelegram: "@nurzhan_action",
    contactWhatsapp: null,
    averageRating: 4.0,
    reviewCount: 5,
    boosts: [],
  },
  {
    email: "gulnaz.smailova@creator-seed.kz",
    name: "Гульназ Смаилова",
    fullName: "Гульназ Смаилова",
    title: "Красота и макияж",
    bio: "Визажист с 5-летним опытом. Снимаю туториалы по макияжу, обзоры новинок косметики, трансформации. Мои подписчики доверяют моим рекомендациям — конверсия в покупку до 8% по промокодам.",
    city: "Karaganda",
    age: 27,
    availability: "available",
    verified: false,
    categories: ["Krasota"],
    platforms: [
      { name: "Instagram", handle: "@gulnaz_makeup", url: "https://instagram.com/gulnaz_makeup", followers: 78000 },
      { name: "TikTok", handle: "@gulnaz.beauty", url: "https://tiktok.com/@gulnaz.beauty", followers: 52000 },
    ],
    minimumRate: 18000,
    priceItems: [
      { label: "Instagram Reels туториал", price: 22000, sortOrder: 0 },
      { label: "TikTok обзор продукта", price: 18000, sortOrder: 1 },
      { label: "Stories обзор (серия 5 шт)", price: 12000, sortOrder: 2 },
    ],
    contactTelegram: "@gulnaz_beauty",
    contactWhatsapp: "+77031234527",
    averageRating: 4.5,
    reviewCount: 14,
    boosts: [],
  },
  {
    email: "arsen.kalibekov@creator-seed.kz",
    name: "Арсен Калибеков",
    fullName: "Арсен Калибеков",
    title: "Стритрейсинг и дрифт",
    bio: "Снимаю контент про автоспорт в Казахстане: дрифт-тренировки, стритрейсинг, тюнинг. Мои видео — это эмоции и скорость. Подхожу для рекламы шин, масел, автозапчастей, тюнинг-студий.",
    city: "Almaty",
    age: 26,
    availability: "busy",
    verified: false,
    categories: ["Avto", "Sport"],
    platforms: [
      { name: "TikTok", handle: "@arsen_drift", url: "https://tiktok.com/@arsen_drift", followers: 145000 },
      { name: "YouTube", handle: "@ArsenDrift", url: "https://youtube.com/@ArsenDrift", followers: 38000 },
    ],
    minimumRate: 20000,
    priceItems: [
      { label: "TikTok дрифт-ролик с интеграцией", price: 20000, sortOrder: 0 },
      { label: "YouTube видео с тюнинг-процессом", price: 45000, sortOrder: 1 },
    ],
    contactTelegram: "@arsen_drift",
    contactWhatsapp: "+77041234528",
    averageRating: 4.3,
    reviewCount: 7,
    boosts: [],
  },
  {
    email: "akmaral.yessimova@creator-seed.kz",
    name: "Акмарал Есимова",
    fullName: "Акмарал Есимова",
    title: "Мемы на казахском",
    bio: "Создаю мемный контент полностью на казахском языке. Мои ролики ориентированы на казахоязычную аудиторию — это уникальная ниша. Аудитория: 16-30 лет, южные регионы. Отлично подхожу для рекламы телеком-операторов, FMCG.",
    city: "Shymkent",
    age: 21,
    availability: "available",
    verified: false,
    categories: ["Memy"],
    platforms: [
      { name: "TikTok", handle: "@akmaral_meme", url: "https://tiktok.com/@akmaral_meme", followers: 88000 },
    ],
    minimumRate: 10000,
    priceItems: [
      { label: "TikTok мем на казахском", price: 10000, sortOrder: 0 },
      { label: "Серия из 5 мемов", price: 40000, sortOrder: 1 },
    ],
    contactTelegram: "@akmaral_meme",
    contactWhatsapp: "+77051234529",
    averageRating: 0,
    reviewCount: 0,
    boosts: [],
  },
  {
    email: "ilyas.zhaksylykov@creator-seed.kz",
    name: "Ильяс Жаксылыков",
    fullName: "Ильяс Жаксылыков",
    title: "Спорт и единоборства",
    bio: "Тренер по боксу и MMA. Снимаю тренировочный контент, мотивационные ролики, обзоры экипировки. Моя аудитория — парни 18-35 лет. Работал с BringSport, Everlast KZ. Могу организовать съёмку в зале с бойцами.",
    city: "Aktau",
    age: 30,
    availability: "partially_available",
    verified: false,
    categories: ["Sport"],
    platforms: [
      { name: "TikTok", handle: "@ilyas_fight", url: "https://tiktok.com/@ilyas_fight", followers: 67000 },
      { name: "Instagram", handle: "@ilyas.mma", url: "https://instagram.com/ilyas.mma", followers: 42000 },
    ],
    minimumRate: 18000,
    priceItems: [
      { label: "TikTok тренировка / бой", price: 18000, sortOrder: 0 },
      { label: "Instagram Reels мотивация", price: 15000, sortOrder: 1 },
      { label: "Обзор экипировки", price: 22000, sortOrder: 2 },
    ],
    contactTelegram: "@ilyas_fight",
    contactWhatsapp: "+77061234530",
    averageRating: 4.4,
    reviewCount: 8,
    boosts: [],
  },
  {
    email: "anel.abilkasymova@creator-seed.kz",
    name: "Анель Абилкасымова",
    fullName: "Анель Абилкасымова",
    title: "Кулинарный блог",
    bio: "Готовлю казахские и мировые блюда в формате коротких видео. Рецепты просты и повторяемы. Мои ролики часто сохраняют — средний save rate 12%. Подхожу для рекламы продуктов питания, техники для кухни, доставки продуктов.",
    city: "Astana",
    age: 29,
    availability: "available",
    verified: false,
    categories: ["Obzory"],
    platforms: [
      { name: "TikTok", handle: "@anel_cooking", url: "https://tiktok.com/@anel_cooking", followers: 98000 },
      { name: "Instagram", handle: "@anel.kitchen", url: "https://instagram.com/anel.kitchen", followers: 61000 },
    ],
    minimumRate: 16000,
    priceItems: [
      { label: "TikTok рецепт с продуктом", price: 16000, sortOrder: 0 },
      { label: "Instagram Reels готовка", price: 20000, sortOrder: 1 },
      { label: "Серия из 3 рецептов", price: 42000, sortOrder: 2 },
    ],
    contactTelegram: "@anel_cooking",
    contactWhatsapp: "+77071234531",
    averageRating: 4.6,
    reviewCount: 11,
    boosts: [],
  },
  {
    email: "sanzhar.musin@creator-seed.kz",
    name: "Санжар Мусин",
    fullName: "Санжар Мусин",
    title: "Кино и мемы",
    bio: "Делаю комедийные нарезки из фильмов: добавляю мемные субтитры, озвучку, ситуации. Мои ролики — это гибрид кинонарезки и мема. Аудитория — 16-28 лет, обоих полов. Отлично подхожу для рекламы развлечений, еды, сервисов.",
    city: "Almaty",
    age: 22,
    availability: "available",
    verified: false,
    categories: ["KinoNarezki", "Memy"],
    platforms: [
      { name: "TikTok", handle: "@sanzhar_memes", url: "https://tiktok.com/@sanzhar_memes", followers: 195000 },
      { name: "Instagram", handle: "@sanzhar.clips", url: "https://instagram.com/sanzhar.clips", followers: 45000 },
    ],
    minimumRate: 20000,
    priceItems: [
      { label: "TikTok мемная нарезка", price: 20000, sortOrder: 0 },
      { label: "Серия из 5 нарезок", price: 80000, sortOrder: 1 },
    ],
    contactTelegram: "@sanzhar_memes",
    contactWhatsapp: null,
    averageRating: 4.3,
    reviewCount: 10,
    boosts: [],
  },
  {
    email: "daria.kim@creator-seed.kz",
    name: "Дарья Ким",
    fullName: "Дарья Ким",
    title: "K-beauty и корейская культура",
    bio: "Рассказываю о корейской косметике, K-pop культуре, корейской еде. Моя аудитория обожает Корею и доверяет моим рекомендациям. Работала с Innisfree, Etude House, корейскими ресторанами Алматы. Снимаю на русском и казахском.",
    city: "Almaty",
    age: 23,
    availability: "available",
    verified: false,
    categories: ["Krasota", "Obzory"],
    platforms: [
      { name: "TikTok", handle: "@daria_kbeauty", url: "https://tiktok.com/@daria_kbeauty", followers: 72000 },
      { name: "Instagram", handle: "@daria.kbeauty", url: "https://instagram.com/daria.kbeauty", followers: 48000 },
    ],
    minimumRate: 18000,
    priceItems: [
      { label: "TikTok K-beauty обзор", price: 18000, sortOrder: 0 },
      { label: "Instagram Reels рутина ухода", price: 22000, sortOrder: 1 },
      { label: "Комплекс TikTok + Reels", price: 35000, sortOrder: 2 },
    ],
    contactTelegram: "@daria_kbeauty",
    contactWhatsapp: "+77091234533",
    averageRating: 4.5,
    reviewCount: 9,
    boosts: [],
  },
  {
    email: "azamat.yermekov@creator-seed.kz",
    name: "Азамат Ермеков",
    fullName: "Азамат Ермеков",
    title: "Мотоконтент и путешествия",
    bio: "Путешествую по Казахстану на мотоцикле и снимаю дорожный контент. Мои ролики — это красивые пейзажи, приключения и лайфхаки для мотоциклистов. Аудитория — мужчины 25-40 лет, любители свободы и дороги.",
    city: "Aktau",
    age: 32,
    availability: "busy",
    verified: false,
    categories: ["Avto", "MuzykaAtmosfera"],
    platforms: [
      { name: "YouTube", handle: "@azamat_moto", url: "https://youtube.com/@azamat_moto", followers: 35000 },
      { name: "TikTok", handle: "@azamat.ride", url: "https://tiktok.com/@azamat.ride", followers: 48000 },
      { name: "Instagram", handle: "@azamat_motolife", url: "https://instagram.com/azamat_motolife", followers: 22000 },
    ],
    minimumRate: 15000,
    priceItems: [
      { label: "TikTok дорожный ролик", price: 15000, sortOrder: 0 },
      { label: "YouTube видео из поездки", price: 35000, sortOrder: 1 },
      { label: "Instagram Reels mood-ride", price: 18000, sortOrder: 2 },
    ],
    contactTelegram: "@azamat_moto",
    contactWhatsapp: "+77011234534",
    averageRating: 0,
    reviewCount: 0,
    boosts: [],
  },
  {
    email: "zhuldyz.aubakirova@creator-seed.kz",
    name: "Жулдыз Аубакирова",
    fullName: "Жулдыз Аубакирова",
    title: "Детский контент и обучение",
    bio: "Создаю образовательный контент для детей: развивающие ролики, мультфильмы, обзоры детских товаров. Моя аудитория — мамы 25-38 лет. Работала с Детский мир, LEGO KZ, образовательными платформами.",
    city: "Astana",
    age: 31,
    availability: "available",
    verified: true,
    categories: ["Multfilmy", "Obzory"],
    platforms: [
      { name: "YouTube", handle: "@zhuldyz_kids", url: "https://youtube.com/@zhuldyz_kids", followers: 92000 },
      { name: "TikTok", handle: "@zhuldyz.kids", url: "https://tiktok.com/@zhuldyz.kids", followers: 55000 },
    ],
    minimumRate: 25000,
    priceItems: [
      { label: "YouTube детский обзор", price: 35000, sortOrder: 0 },
      { label: "TikTok развивающий ролик", price: 18000, sortOrder: 1 },
      { label: "Серия из 3 обучающих видео", price: 60000, sortOrder: 2 },
    ],
    contactTelegram: "@zhuldyz_kids",
    contactWhatsapp: "+77021234535",
    averageRating: 4.8,
    reviewCount: 20,
    boosts: [],
  },
  {
    email: "kuat.zhunussov@creator-seed.kz",
    name: "Куат Жунусов",
    fullName: "Куат Жунусов",
    title: "Обзоры смартфонов",
    bio: "Сравниваю смартфоны в формате «какой купить»: простым языком, с реальными тестами камеры, батареи, игр. Мой канал помогает людям выбрать телефон без переплаты. Работал с Alser, Mechta, Sulpak.",
    city: "Karaganda",
    age: 24,
    availability: "available",
    verified: false,
    categories: ["Obzory"],
    platforms: [
      { name: "YouTube", handle: "@kuat_phones", url: "https://youtube.com/@kuat_phones", followers: 48000 },
      { name: "TikTok", handle: "@kuat.tech", url: "https://tiktok.com/@kuat.tech", followers: 35000 },
    ],
    minimumRate: 15000,
    priceItems: [
      { label: "YouTube обзор смартфона", price: 30000, sortOrder: 0 },
      { label: "TikTok мини-сравнение", price: 12000, sortOrder: 1 },
      { label: "YouTube Shorts распаковка", price: 10000, sortOrder: 2 },
    ],
    contactTelegram: "@kuat_tech",
    contactWhatsapp: "+77031234536",
    averageRating: 4.1,
    reviewCount: 5,
    boosts: [],
  },
  {
    email: "aida.tursunova@creator-seed.kz",
    name: "Аида Турсунова",
    fullName: "Аида Турсунова",
    title: "Йога и медитация",
    bio: "Сертифицированный инструктор йоги. Снимаю мини-практики, медитации, обзоры ковриков и одежды для йоги. Моя аудитория — женщины 25-45 лет, которые заботятся о ментальном здоровье. Спокойный, вдумчивый контент.",
    city: "Almaty",
    age: 29,
    availability: "available",
    verified: false,
    categories: ["Sport", "MuzykaAtmosfera"],
    platforms: [
      { name: "Instagram", handle: "@aida_yoga", url: "https://instagram.com/aida_yoga", followers: 42000 },
      { name: "YouTube", handle: "@AidaYoga", url: "https://youtube.com/@AidaYoga", followers: 18000 },
    ],
    minimumRate: 15000,
    priceItems: [
      { label: "Instagram Reels мини-практика", price: 15000, sortOrder: 0 },
      { label: "YouTube полная практика (20 мин)", price: 30000, sortOrder: 1 },
      { label: "Stories обзор продукта", price: 8000, sortOrder: 2 },
    ],
    contactTelegram: "@aida_yoga",
    contactWhatsapp: "+77041234537",
    averageRating: 4.7,
    reviewCount: 12,
    boosts: [],
  },
  {
    email: "dias.nauryzbaev@creator-seed.kz",
    name: "Диас Наурызбаев",
    fullName: "Диас Наурызбаев",
    title: "Музыкальные нарезки и тренды",
    bio: "Создаю музыкальные нарезки: трендовые звуки, липсинк, танцевальные ролики. Мои видео быстро набирают охват благодаря использованию актуальных трендов. Идеально для рекламы молодёжных брендов, приложений, мероприятий.",
    city: "Pavlodar",
    age: 19,
    availability: "available",
    verified: false,
    categories: ["MuzykaAtmosfera", "Memy"],
    platforms: [
      { name: "TikTok", handle: "@dias_music", url: "https://tiktok.com/@dias_music", followers: 125000 },
    ],
    minimumRate: 12000,
    priceItems: [
      { label: "TikTok трендовый ролик", price: 12000, sortOrder: 0 },
      { label: "Серия из 3 трендов", price: 30000, sortOrder: 1 },
    ],
    contactTelegram: "@dias_music",
    contactWhatsapp: null,
    averageRating: 0,
    reviewCount: 0,
    boosts: [],
  },
  {
    email: "saule.balgabaeva@creator-seed.kz",
    name: "Сауле Балгабаева",
    fullName: "Сауле Балгабаева",
    title: "Обзоры книг и саморазвитие",
    bio: "Рассказываю о книгах, курсах, приложениях для саморазвития. Формат: короткие обзоры книг за 60 секунд, подборки, мотивационные посты. Моя аудитория — образованные люди 22-38 лет, которые хотят расти.",
    city: "Astana",
    age: 26,
    availability: "partially_available",
    verified: false,
    categories: ["Obzory", "Podkasty"],
    platforms: [
      { name: "TikTok", handle: "@saule_books", url: "https://tiktok.com/@saule_books", followers: 58000 },
      { name: "Instagram", handle: "@saule.reads", url: "https://instagram.com/saule.reads", followers: 35000 },
    ],
    minimumRate: 12000,
    priceItems: [
      { label: "TikTok обзор книги/приложения", price: 12000, sortOrder: 0 },
      { label: "Instagram Reels подборка", price: 15000, sortOrder: 1 },
    ],
    contactTelegram: "@saule_books",
    contactWhatsapp: "+77061234539",
    averageRating: 4.4,
    reviewCount: 7,
    boosts: [],
  },
  {
    email: "raimbek.tursynov@creator-seed.kz",
    name: "Раимбек Турсынов",
    fullName: "Раимбек Турсынов",
    title: "Казахский мем-лорд",
    bio: "Делаю вирусный мемный контент. Мои мемы расходятся по чатам и группам. Формат: скетчи, пародии, ситуации «только в Казахстане». Средний охват ролика — 150K. Подхожу для всего, что нужно сделать смешным.",
    city: "Shymkent",
    age: 20,
    availability: "available",
    verified: false,
    categories: ["Memy"],
    platforms: [
      { name: "TikTok", handle: "@raimbek_memes", url: "https://tiktok.com/@raimbek_memes", followers: 230000 },
      { name: "Instagram", handle: "@raimbek.lol", url: "https://instagram.com/raimbek.lol", followers: 85000 },
    ],
    minimumRate: 25000,
    priceItems: [
      { label: "TikTok мемный ролик", price: 25000, sortOrder: 0 },
      { label: "Instagram Reels скетч", price: 28000, sortOrder: 1 },
      { label: "Серия из 5 мемов", price: 100000, sortOrder: 2 },
    ],
    contactTelegram: "@raimbek_memes",
    contactWhatsapp: "+77071234540",
    averageRating: 4.2,
    reviewCount: 8,
    boosts: [],
  },
  {
    email: "ainur.bisenbaeva@creator-seed.kz",
    name: "Айнур Бисенбаева",
    fullName: "Айнур Бисенбаева",
    title: "Nail-арт и маникюр",
    bio: "Мастер маникюра с 7-летним опытом. Снимаю процесс работы в ASMR-формате: покрытие, дизайн, nail-арт. Мои ролики расслабляют и вдохновляют. Работаю с брендами гель-лаков, лампами, инструментами для маникюра.",
    city: "Almaty",
    age: 28,
    availability: "partially_available",
    verified: false,
    categories: ["Krasota"],
    platforms: [
      { name: "TikTok", handle: "@ainur_nails", url: "https://tiktok.com/@ainur_nails", followers: 82000 },
      { name: "Instagram", handle: "@ainur.nailart", url: "https://instagram.com/ainur.nailart", followers: 55000 },
    ],
    minimumRate: 14000,
    priceItems: [
      { label: "TikTok ASMR маникюр", price: 14000, sortOrder: 0 },
      { label: "Instagram Reels nail-арт", price: 16000, sortOrder: 1 },
      { label: "Обзор продукта (Reels + Stories)", price: 25000, sortOrder: 2 },
    ],
    contactTelegram: "@ainur_nails",
    contactWhatsapp: "+77081234541",
    averageRating: 4.6,
    reviewCount: 15,
    boosts: [],
  },
  {
    email: "daulet.zhakupov@creator-seed.kz",
    name: "Даулет Жакупов",
    fullName: "Даулет Жакупов",
    title: "Геймплей и стримы CS2",
    bio: "Профессиональный игрок CS2, бывший участник FACEIT Pro League. Снимаю хайлайты, обучающие ролики, клатч-подборки. Моя аудитория — хардкорные геймеры 16-28 лет. Идеально для рекламы периферии, энергетиков, кибер-ивентов.",
    city: "Astana",
    age: 22,
    availability: "busy",
    verified: false,
    categories: ["Geympley"],
    platforms: [
      { name: "TikTok", handle: "@daulet_cs2", url: "https://tiktok.com/@daulet_cs2", followers: 105000 },
      { name: "YouTube", handle: "@DauletCS", url: "https://youtube.com/@DauletCS", followers: 62000 },
    ],
    minimumRate: 20000,
    priceItems: [
      { label: "TikTok клатч/хайлайт", price: 15000, sortOrder: 0 },
      { label: "YouTube обзор (5-10 мин)", price: 35000, sortOrder: 1 },
      { label: "Стрим-интеграция", price: 50000, sortOrder: 2 },
    ],
    contactTelegram: "@daulet_cs2",
    contactWhatsapp: null,
    averageRating: 4.0,
    reviewCount: 4,
    boosts: [],
  },
  {
    email: "laura.ibragimova@creator-seed.kz",
    name: "Лаура Ибрагимова",
    fullName: "Лаура Ибрагимова",
    title: "Travel-контент Казахстан",
    bio: "Путешествую по Казахстану и снимаю кинематографичные ролики: Чарынский каньон, Кольсай, Бурабай, городские виды. Мой контент используют турфирмы, отели, авиакомпании. Снимаю на дрон DJI Mini 4 Pro.",
    city: "Almaty",
    age: 27,
    availability: "busy",
    verified: true,
    categories: ["MuzykaAtmosfera", "Obzory"],
    platforms: [
      { name: "Instagram", handle: "@laura_travel_kz", url: "https://instagram.com/laura_travel_kz", followers: 95000 },
      { name: "TikTok", handle: "@laura.travel", url: "https://tiktok.com/@laura.travel", followers: 68000 },
      { name: "YouTube", handle: "@LauraTravelKZ", url: "https://youtube.com/@LauraTravelKZ", followers: 25000 },
    ],
    minimumRate: 30000,
    priceItems: [
      { label: "TikTok travel-ролик", price: 25000, sortOrder: 0 },
      { label: "Instagram Reels с дрона", price: 30000, sortOrder: 1 },
      { label: "YouTube travel-видео (5-10 мин)", price: 55000, sortOrder: 2 },
      { label: "Комплекс все платформы", price: 90000, sortOrder: 3 },
    ],
    contactTelegram: "@laura_travel",
    contactWhatsapp: "+77011234543",
    averageRating: 4.9,
    reviewCount: 23,
    boosts: [],
  },
  {
    email: "yerbol.ospanov@creator-seed.kz",
    name: "Ербол Оспанов",
    fullName: "Ербол Оспанов",
    title: "Нарезки из подкастов",
    bio: "Монтирую нарезки из популярных подкастов: выбираю самые интересные моменты, добавляю субтитры, музыку. Мои ролики помогают подкастам набирать новых подписчиков. Также делаю нарезки на заказ для корпоративных подкастов.",
    city: "Pavlodar",
    age: 25,
    availability: "available",
    verified: false,
    categories: ["Podkasty", "KinoNarezki"],
    platforms: [
      { name: "TikTok", handle: "@yerbol_clips", url: "https://tiktok.com/@yerbol_clips", followers: 45000 },
      { name: "Instagram", handle: "@yerbol.podcast.clips", url: "https://instagram.com/yerbol.podcast.clips", followers: 18000 },
    ],
    minimumRate: 8000,
    priceItems: [
      { label: "TikTok нарезка из подкаста", price: 8000, sortOrder: 0 },
      { label: "Серия из 5 нарезок", price: 32000, sortOrder: 1 },
      { label: "Монтаж полного выпуска", price: 25000, sortOrder: 2 },
    ],
    contactTelegram: "@yerbol_clips",
    contactWhatsapp: "+77021234544",
    averageRating: 3.9,
    reviewCount: 3,
    boosts: [],
  },
  {
    email: "togzhan.karimova@creator-seed.kz",
    name: "Тогжан Каримова",
    fullName: "Тогжан Каримова",
    title: "Мультфильмы и детский контент",
    bio: "Создаю контент для детей 3-10 лет: нарезки из мультфильмов с озвучкой на казахском, развивающие ролики, обзоры игрушек. Моя аудитория — мамы Казахстана. Работала с Hasbro KZ, Детский мир, образовательные приложения.",
    city: "Karaganda",
    age: 30,
    availability: "available",
    verified: false,
    categories: ["Multfilmy"],
    platforms: [
      { name: "YouTube", handle: "@togzhan_kids", url: "https://youtube.com/@togzhan_kids", followers: 65000 },
      { name: "TikTok", handle: "@togzhan.cartoon", url: "https://tiktok.com/@togzhan.cartoon", followers: 42000 },
    ],
    minimumRate: 15000,
    priceItems: [
      { label: "YouTube детский ролик", price: 25000, sortOrder: 0 },
      { label: "TikTok мульт-нарезка", price: 12000, sortOrder: 1 },
      { label: "Обзор игрушки", price: 18000, sortOrder: 2 },
    ],
    contactTelegram: "@togzhan_kids",
    contactWhatsapp: "+77031234545",
    averageRating: 4.3,
    reviewCount: 6,
    boosts: [],
  },
  {
    email: "sultan.moldabekov@creator-seed.kz",
    name: "Султан Молдабеков",
    fullName: "Султан Молдабеков",
    title: "Кинонарезки sci-fi и фэнтези",
    bio: "Специализируюсь на нарезках из фантастики и фэнтези: Marvel, Star Wars, Dune, Властелин Колец. Добавляю эпичную музыку, визуальные эффекты, текст. Мои ролики создают ощущение трейлера.",
    city: "Aktau",
    age: 21,
    availability: "available",
    verified: false,
    categories: ["KinoNarezki"],
    platforms: [
      { name: "TikTok", handle: "@sultan_scifi", url: "https://tiktok.com/@sultan_scifi", followers: 78000 },
    ],
    minimumRate: 12000,
    priceItems: [
      { label: "TikTok sci-fi нарезка", price: 12000, sortOrder: 0 },
      { label: "Серия из 3 нарезок", price: 30000, sortOrder: 1 },
    ],
    contactTelegram: "@sultan_scifi",
    contactWhatsapp: null,
    averageRating: 0,
    reviewCount: 0,
    boosts: [],
  },
  {
    email: "elmira.abilova@creator-seed.kz",
    name: "Эльмира Абилова",
    fullName: "Эльмира Абилова",
    title: "Волосы и уход",
    bio: "Стилист-парикмахер с 10-летним стажем. Снимаю трансформации, уход за волосами, обзоры профессиональной косметики. Мои ролики «до/после» стабильно набирают 100K+. Работаю с Kérastase, L'Oréal Pro, салонами красоты.",
    city: "Shymkent",
    age: 33,
    availability: "partially_available",
    verified: false,
    categories: ["Krasota"],
    platforms: [
      { name: "Instagram", handle: "@elmira_hair", url: "https://instagram.com/elmira_hair", followers: 68000 },
      { name: "TikTok", handle: "@elmira.hairstyle", url: "https://tiktok.com/@elmira.hairstyle", followers: 45000 },
    ],
    minimumRate: 16000,
    priceItems: [
      { label: "TikTok трансформация", price: 16000, sortOrder: 0 },
      { label: "Instagram Reels до/после", price: 20000, sortOrder: 1 },
      { label: "Обзор продукта (видео + Stories)", price: 28000, sortOrder: 2 },
    ],
    contactTelegram: "@elmira_hair",
    contactWhatsapp: "+77051234547",
    averageRating: 4.5,
    reviewCount: 11,
    boosts: [],
  },
  {
    email: "olzhas.sarsenbaev@creator-seed.kz",
    name: "Олжас Сарсенбаев",
    fullName: "Олжас Сарсенбаев",
    title: "Спорт и воркаут",
    bio: "Воркаут-атлет и тренер. Снимаю тренировки на улице, челленджи, мотивационный контент. Моя аудитория — парни 16-30 лет, которые тренируются на спортплощадках. Работал с Adidas KZ, Decathlon.",
    city: "Karaganda",
    age: 25,
    availability: "available",
    verified: false,
    categories: ["Sport"],
    platforms: [
      { name: "TikTok", handle: "@olzhas_workout", url: "https://tiktok.com/@olzhas_workout", followers: 55000 },
      { name: "Instagram", handle: "@olzhas.bar", url: "https://instagram.com/olzhas.bar", followers: 28000 },
    ],
    minimumRate: 10000,
    priceItems: [
      { label: "TikTok воркаут-ролик", price: 10000, sortOrder: 0 },
      { label: "Instagram Reels тренировка", price: 12000, sortOrder: 1 },
      { label: "Челлендж с продуктом", price: 18000, sortOrder: 2 },
    ],
    contactTelegram: "@olzhas_workout",
    contactWhatsapp: "+77061234548",
    averageRating: 0,
    reviewCount: 0,
    boosts: [],
  },
  {
    email: "madina.tulebaeva@creator-seed.kz",
    name: "Мадина Тулебаева",
    fullName: "Мадина Тулебаева",
    title: "Кино-нарезки комедия",
    bio: "Монтирую смешные нарезки из комедий и ситкомов. Мой формат: мемный overlay на кадрах из фильмов. Ролики легко смотрятся и часто шерятся. Аудитория: 16-35 лет, все полы. Подхожу для рекламы доставки еды, развлечений, приложений.",
    city: "Astana",
    age: 23,
    availability: "available",
    verified: false,
    categories: ["KinoNarezki", "Memy"],
    platforms: [
      { name: "TikTok", handle: "@madina_funny", url: "https://tiktok.com/@madina_funny", followers: 165000 },
      { name: "Instagram", handle: "@madina.funclips", url: "https://instagram.com/madina.funclips", followers: 38000 },
    ],
    minimumRate: 18000,
    priceItems: [
      { label: "TikTok комедийная нарезка", price: 18000, sortOrder: 0 },
      { label: "Серия из 5 нарезок", price: 70000, sortOrder: 1 },
    ],
    contactTelegram: "@madina_funny",
    contactWhatsapp: "+77071234549",
    averageRating: 4.1,
    reviewCount: 6,
    boosts: [],
  },
  {
    email: "berik.zhumabay@creator-seed.kz",
    name: "Берик Жумабай",
    fullName: "Берик Жумабай",
    title: "Геймплей и мобильные игры",
    bio: "Снимаю контент по мобильным играм: PUBG Mobile, Genshin Impact, Mobile Legends. Делаю гайды, хайлайты, мемные моменты. Аудитория — мобильные геймеры 14-25 лет. Подхожу для рекламы приложений, аксессуаров для телефонов.",
    city: "Shymkent",
    age: 20,
    availability: "available",
    verified: false,
    categories: ["Geympley"],
    platforms: [
      { name: "TikTok", handle: "@berik_gaming", url: "https://tiktok.com/@berik_gaming", followers: 72000 },
      { name: "YouTube", handle: "@BerikGaming", url: "https://youtube.com/@BerikGaming", followers: 30000 },
    ],
    minimumRate: 8000,
    priceItems: [
      { label: "TikTok геймплей-ролик", price: 8000, sortOrder: 0 },
      { label: "YouTube гайд (5-10 мин)", price: 20000, sortOrder: 1 },
      { label: "Серия из 5 TikTok", price: 32000, sortOrder: 2 },
    ],
    contactTelegram: "@berik_gaming",
    contactWhatsapp: "+77081234550",
    averageRating: 3.7,
    reviewCount: 2,
    boosts: [],
  },
  {
    email: "karlygash.nurbekova@creator-seed.kz",
    name: "Карлыгаш Нурбекова",
    fullName: "Карлыгаш Нурбекова",
    title: "Рецепты и домашняя кухня",
    bio: "Готовлю традиционные казахские блюда и адаптирую их для молодёжи: быстро, красиво, вкусно. Мой контент — это уют и ностальгия. Аудитория: девушки 20-35 лет. Работала с Magnum, Arbuz.kz, бренды масла и муки.",
    city: "Pavlodar",
    age: 31,
    availability: "partially_available",
    verified: false,
    categories: ["Obzory"],
    platforms: [
      { name: "TikTok", handle: "@karlygash_cook", url: "https://tiktok.com/@karlygash_cook", followers: 62000 },
      { name: "Instagram", handle: "@karlygash.kitchen", url: "https://instagram.com/karlygash.kitchen", followers: 38000 },
    ],
    minimumRate: 12000,
    priceItems: [
      { label: "TikTok рецепт с продуктом", price: 12000, sortOrder: 0 },
      { label: "Instagram Reels готовка", price: 15000, sortOrder: 1 },
      { label: "Серия из 3 рецептов", price: 30000, sortOrder: 2 },
    ],
    contactTelegram: "@karlygash_cook",
    contactWhatsapp: "+77091234551",
    averageRating: 4.4,
    reviewCount: 8,
    boosts: [],
  },
  {
    email: "nurlan.alibekov@creator-seed.kz",
    name: "Нурлан Алибеков",
    fullName: "Нурлан Алибеков",
    title: "Кинонарезки с озвучкой",
    bio: "Озвучиваю нарезки из фильмов своим голосом: драматично, с юмором, с интригой. Мой голос стал узнаваемым — подписчики ждут каждый новый ролик. Могу озвучить рекламный ролик или сделать нарезку-интеграцию.",
    city: "Aktau",
    age: 26,
    availability: "available",
    verified: false,
    categories: ["KinoNarezki"],
    platforms: [
      { name: "TikTok", handle: "@nurlan_voice", url: "https://tiktok.com/@nurlan_voice", followers: 95000 },
      { name: "Instagram", handle: "@nurlan.voiceover", url: "https://instagram.com/nurlan.voiceover", followers: 22000 },
    ],
    minimumRate: 14000,
    priceItems: [
      { label: "TikTok нарезка с озвучкой", price: 14000, sortOrder: 0 },
      { label: "Озвучка рекламного ролика", price: 25000, sortOrder: 1 },
      { label: "Серия из 5 нарезок", price: 55000, sortOrder: 2 },
    ],
    contactTelegram: "@nurlan_voice",
    contactWhatsapp: null,
    averageRating: 4.3,
    reviewCount: 7,
    boosts: [],
  },
];
